### ISSUE TITLE
The graph for time complexity analysis is not updating for different complexities

### ISSUE THREAD

**Issue by ash-k121** [multiverseweb/Dataverse#10]
Please assign this issue to me under gssoc -ext 24
![image](https://github.com/user-attachments/assets/52372ae1-ecde-4fbe-8318-3f5fde405db9)

**Comment by multiverseweb** [comment]
@ash-k121 you opened the issue on wrong project. Try opening on [CodeIt](https://github.com/multiverseweb/CodeIt).
