### ISSUE TITLE
Ensure the favicon is set with multiple sizes for different devices

### ISSUE THREAD

**Issue by GauriSachan** [multiverseweb/Dataverse#102]
hey i can do this can you assign me this issue under the labels of hacktoberfest,gssoc-ext and appropriate level?

### Current Behaviour

- Describe the current situation or problem you're facing. Be specific about what’s lacking or what can be improved.

### Proposed Solution

- Describe the feature or enhancement you'd like to see implemented.

### Screenshot/Mockup (Optional)

- Attach any relevant visuals or mockups that illustrate your idea.

### Alternatives Considered

- List any alternative solutions or features you’ve considered before suggesting this one.

### Additional Context

- Include any extra details, links, or documents that can help clarify or support your feature request.

### Requirement/Document

- Share any document that outlines or supports this feature request.

**Comment by jency1** [comment]
@GauriSachan Describe the current behaviour  and proposed solution. And attach any screenshot if possible.
