### ISSUE TITLE
FEATURE : Automated Greeting Workflow

### ISSUE THREAD

**Issue by archanasingh11** [multiverseweb/Dataverse#103]
## Description

I propose the implementation of a GitHub Actions workflow named **"Greetings"** to automatically greet users when they open new issues or pull requests. This will enhance communication with contributors and provide immediate acknowledgment of their submissions.

### Key Features:
- **Automatic Greetings**: 
  - **For Issues**: When a user opens an issue, they will receive an automatic message like:  
    "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: When a pull request is submitted, the user will receive a message such as:  
    "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

### Benefits:
- **Improved Communication**: Immediate, automated acknowledgment for contributors helps improve transparency and engagement.
- **Contributor Experience**: Contributors feel valued and informed about the next steps as soon as they submit their issue or pull request.
- **Time Efficiency**: Maintainers save time on manual acknowledgments, allowing more focus on reviewing contributions.

Implementing this feature will enhance contributor experience and streamline communication for the project.

Please @multiverseweb assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2", "level3"

**Comment by multiverseweb** [comment]
@archanasingh11, the greeting workflow has been already, so I'm closing this issue.
