### ISSUE TITLE
Feature: Changing the logo and Project's name font size.

### ISSUE THREAD

**Issue by MimanshaKaur** [multiverseweb/Dataverse#108]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

- the logo is very small in size and not looking related to coding theme.
- also, the font style and font size  and font color of CodeIt (Project name) is not that accurate.

### Proposed Solution

- i will design a new attractive and eye-catching logo related to coding theme and add it.
- i will make the project_name (CodeIt) little large in size and bold and also increase the opacity , so that it can become more eye-catching and can be differentiated with other options present on the header nav-bar.

### Screenshot/Mockup (Optional)
![Screenshot 2024-10-10 195343](https://github.com/user-attachments/assets/afb7dec4-e0e5-4caa-adea-20ef217d7b59)

@multiverseweb please give me the chance to solve this issue . please add labels of gssoc-ext and hacktoberfest-accepted on assigning.
Thank You

**Comment by jency1** [comment]
@MimanshaKaur What type of logo will you add ?

**Comment by MimanshaKaur** [comment]
1)
![Screenshot 2024-10-11 083149](https://github.com/user-attachments/assets/1cf0c802-e87e-4bba-8178-df362a3271da)

2)
![Screenshot 2024-10-11 083211](https://github.com/user-attachments/assets/8027a48f-cbf2-4c35-8f0b-62e10d559019)


These type of logos that are designed by focusing on "Coding" as the main theme of project. I think it will give more professional and attractive look to your website...you can either choose first or second logo.. i think first one is better for your website.

After this the name (CodeIt) will be added in gradient color similar to logo's color.

@jency1 please have a look.

**Comment by MimanshaKaur** [comment]
@jency1 these logos are going super well with both the light and dark themes.

**Comment by jency1** [comment]
@MimanshaKaur Ok. I am requesting a review from Project Admin. He will assign you if he wants to change the logo of the website.

**Comment by MimanshaKaur** [comment]
@multiverseweb i think that these logos will surely work well in this project if we focus on main idea (i.e., coding) behind this project and for both light and dark modes.

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..

**Comment by multiverseweb** [comment]
@MimanshaKaur 
![image](https://github.com/user-attachments/assets/dbf73960-ac74-465f-acad-52b3d94c1d26)

The current logo has following features:
- Colourful spectrum - Representing the versatility of CodeIt and its wide range of target users.
- `-.` - Representing coding, as these two symbols are one of the most frequently used symbols in programming languages.
- The font style is `Consolas`, which is used in VS Code consoles.

Would love to discuss better ideas for the logo. Let's get involved [here](https://github.com/multiverseweb/CodeIt/discussions). Please create a new discussion for the same. Looking forward to your ideas!
