### ISSUE TITLE
Feature: Changing Text font style to professional font style with proper alignment and styling.

### ISSUE THREAD

**Issue by MimanshaKaur** [multiverseweb/Dataverse#109]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

- the present font style is not that professional according to a website related to coding or created for coders.
- Text not justify-aligned.
- The highlighted background is used for headings.

### Proposed Solution

- i want to change the text style to any professional font style  so that the website looks more coding/coders focused.
- i will adjust all the text alignments by changing the required ones to justify alignment.
- i want to change the highlighted background headings to headings with gradient styling that too in  uppercase.

### Screenshot/Mockup (Optional)
![Screenshot 2024-10-10 201932](https://github.com/user-attachments/assets/964f2bf9-37c7-46e8-b131-278910351608)

@multiverseweb please assign this task to me. i will be more than happy to work on this issue. Kindly add gssoc-ext and hacktoberfest-accepted labels on assigning.
Thank You.

**Comment by jency1** [comment]
@MimanshaKaur Share the screenshot of the change that you will be implementing.

**Comment by MimanshaKaur** [comment]
![Screenshot 2024-10-11 082726](https://github.com/user-attachments/assets/b48c411d-83b7-4614-9d0a-86f0553cbd00)
 i want to make changes like this:
- professional font-style used for text...that is enhancing the readability of the text.
- all the text written with justify alignment...properly indented.
- beautiful eye-catching gradient headings.

@jency1 please have a look.

**Comment by jency1** [comment]
@MimanshaKaur Ok assigning. Make sure the content , images and layout remains the same.

**Comment by MimanshaKaur** [comment]
@jency1 thank you for assigning...sure i will keep them same.👍

**Comment by multiverseweb** [comment]
> Have an idea for a new feature? Please fill out the sections below. 😊
> 
> ### Current Behaviour
> * the present font style is not that professional according to a website related to coding or created for coders.
> * Text not justify-aligned.
> * The highlighted background is used for headings.
> 
> ### Proposed Solution
> * i want to change the text style to any professional font style  so that the website looks more coding/coders focused.
> * i will adjust all the text alignments by changing the required ones to justify alignment.
> * i want to change the highlighted background headings to headings with gradient styling that too in  uppercase.
> 
> ### Screenshot/Mockup (Optional)
> ![Screenshot 2024-10-10 201932](https://private-user-images.githubusercontent.com/134724715/375431726-964f2bf9-37c7-46e8-b131-278910351608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NzQyOTQsIm5iZiI6MTcyODc3Mzk5NCwicGF0aCI6Ii8xMzQ3MjQ3MTUvMzc1NDMxNzI2LTk2NGYyYmY5LTM3YzctNDZlOC1iMTMxLTI3ODkxMDM1MTYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQyMjU5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTY1MGU3ZjRkOTlmNWQ1Y2U5M2M0ZjUyMDdhODljY2M1Yjk5YmI2ZTVjYzg2ZTA0MWY4MzYzYWIzOTQ3YzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bbHsNo6DHwNrhGErah-Kg9BnZtg6s5CjP-xBjHmeN_Y)
> 
> @multiverseweb please assign this task to me. i will be more than happy to work on this issue. Kindly add gssoc-ext and hacktoberfest-accepted labels on assigning. Thank You.

Are you working on [CodeIt](https://github.com/multiverseweb/CodeIt) or [Dataverse](https://github.com/multiverseweb/Dataverse)? You raised the issue on Dataverse with the screenshot of CodeIt.

**Comment by MimanshaKaur** [comment]
[AwesomeScreenshot-10_14_2024,12_19_15AM.webm](https://github.com/user-attachments/assets/58c3d72f-3404-4f05-9107-97da52b123c3)

@multiverseweb  there is some issue with deployment links ..actually when i am opening "Dataverse" on GSSOC projects then CodeIt website is opening through deployment link...

and when i am opening "CodeIt - An All in One Tool for Developers" on GSSOC projects then its opening dataverse


@multiverseweb please see this screen recording video and guide me for what should i do next?..

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by multiverseweb** [comment]
> AwesomeScreenshot-10_14_2024.12_19_15AM.webm 
> @multiverseweb there is some issue with deployment links ..actually when i am opening "Dataverse" on GSSOC projects then CodeIt website is opening through deployment link...
> 
> and when i am opening "CodeIt - An All in One Tool for Developers" on GSSOC projects then its opening dataverse
> 
> @multiverseweb please see this screen recording video and guide me for what should i do next?..

@MimanshaKaur Thanks. Will look into the same.

**Comment by MimanshaKaur** [comment]
@multiverseweb is the issue resolved? Can i start working on CodeIt?

**Comment by MimanshaKaur** [comment]
@multiverseweb i am working on this project👍👍
Let's see.. if you are ok with the changes that i do...so you can  merge it and then later on if you change the deployment link then same changes will be done in that too..so i think that there is no such issue in that😊👍

**Comment by MimanshaKaur** [comment]
@multiverseweb there is one thing that needs to be considered!!
i just forked this dataverse repo. and here the code is of dataverse website only. it means that both repositories are OK with their actual codes of their real and same name websites and just their deployment links are interchanged while uploading on GSSOC projects.


Now, the thing is that i raised the issue for CodeIt here!!
Sorry for this..i actually just saw this!!

But as i have observed this Dataverse website, it also has some issues, that i want to resolve :
1) i am thinking of redesigning its login and sign up page which will have properly centered aligned form.
2) a login and sign up page with beautiful theme based background.
3) proper title name

![Screenshot 2024-10-17 003321](https://github.com/user-attachments/assets/482c3728-2e78-4672-a55b-853d9511ec1b)


I will be happy to work on this 😊
if you allow ,so can i work on these issues in DATAVERSE...
@multiverseweb ???

**Comment by MimanshaKaur** [comment]
@multiverseweb See the login form is not in center and title name is "Document" with no logo.
so i will work on this and resolve it for both login and sign up page.

**Comment by MimanshaKaur** [comment]
thank you @multiverseweb

**Comment by MimanshaKaur** [comment]
@multiverseweb  i have created a new issue #164 for this ..please assign it .

**Comment by MimanshaKaur** [comment]
@multiverseweb completed this task in issue #164 👍👍
