### ISSUE TITLE
Add Email Existence Check Before Form Submission

### ISSUE THREAD

**Issue by HarshAgrawal1** [multiverseweb/Dataverse#11]
We need to add a feature that ensures a form submission only proceeds if the provided email exists and by  ensuring that the domain is capable of receiving emails.. Currently, the form can be submitted even if the email ID does not exist, leading to unnecessary data processing and potential errors.

![image](https://github.com/user-attachments/assets/bee768cb-9996-444d-9dae-22c7a4646f95)
![image](https://github.com/user-attachments/assets/93b6ff89-ad01-4a57-90bd-7a0508ddfc17)

Solution:
Backend Validation: Add a check in the backend using MX Record Lookup to verify if the email exists . If not, return an appropriate error message and prevent the form from being submitted.

@multiverseweb Please look into this and assign this issue to me so I can implement the feature and resolve the issue by adding the email existence check before form submission.

**Comment by subikshabamboo** [comment]
Can I contibute to this issue?

**Comment by multiverseweb** [comment]
@HarshAgrawal1 Sure, I'm assigning this to you.

**Comment by Devanshu1603** [comment]
please assign me this issue.

**Comment by HarshAgrawal1** [comment]
@multiverseweb  How can I reach you to discuss this? I have an API to validate email addresses, and I would like to go over the details with you.

**Comment by multiverseweb** [comment]
@HarshAgrawal1 We can chat on [Linkedin](https://www.linkedin.com/in/tejascodes/) or if verbal communication is required, we can schedule a meet.

**Comment by HarshAgrawal1** [comment]
@multiverseweb Okay I sent you request on LinkedIn!
