### ISSUE TITLE
Make the form filling section more dynamic

### ISSUE THREAD

**Issue by ThunderShadows** [multiverseweb/Dataverse#112]
Current Behaviour

- The styling and the responsiveness of the form is static and less interactive.

Proposed Solution

- Make the form section, text area input and the send button more vibrant and responsive to look at.

- Attach any relevant visuals or mockups that illustrate your idea.

@multiverseweb Please assign me this issue. I shall make it more interactive.

**Comment by Vipulsnips** [comment]
Hi @multiverseweb , I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!
