### ISSUE TITLE
Enhance PDF Report with Detailed Financial Summary and Dynamic Plot Inclusion

### ISSUE THREAD

**Issue by Ananya-vastare** [multiverseweb/Dataverse#114]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour
The current PDF report generated by the personal finance tracker lacks detailed financial insights, providing only a summary with limited context. Specifically, it does not clearly separate and present the total amount, income, and expenses, making it harder for users to understand their financial situation at a glance. Additionally, if the plot image is missing, the report fails to inform users about it, resulting in an incomplete or misleading report.

### Proposed Solution

Implement enhancements to the PDF report generation that include:
Detailed Financial Summary: Clearly present the total amount, income, and expenses in separate lines within the report to give users a comprehensive overview of their finances.
Dynamic Plot Inclusion: Add functionality to check if the plot image exists before including it in the PDF. If the image is not found, provide a message in the report indicating that the plot is missing, thus preventing confusion.
Improved Formatting: Utilize better alignment and formatting to enhance readability and ensure a polished look for the report.
Safe Filename Handling: Ensure that the generated PDF file names are sanitized and safe for all operating systems to avoid any issues with file creation.

### Screenshot/Mockup (Optional)

- Attach any relevant visuals or mockups that illustrate your idea.

### Alternatives Considered
Instead of adding detailed summaries and dynamic plot checks, I considered simply enhancing the existing PDF format with minor changes. However, this approach would not address the lack of clarity in financial reporting and the risk of missing plot images.

### Additional Context
This enhancement aims to improve user experience by making financial reporting more informative and visually appealing. The changes will help users better understand their financial status and ensure they receive complete reports.
Additional resources, such as user feedback on the current PDF format and examples of user preferences for financial reporting, could be referenced to support this feature request.

### Requirement/Document
Attached is a document outlining user feedback and preferences regarding the PDF report generation, including specific examples of desired changes and enhancements. [Attach any relevant documents that support this feature request].

- Share any document that outlines or supports this feature request.

**Comment by Ananya-vastare** [comment]
![Uploading Graph.png…]()

**Comment by multiverseweb** [comment]
Hey @Ananya-vastare, similar issue #5 already exists, comment there to get assigned.

**Comment by multiverseweb** [comment]
Hey @Ananya-vastare, similar issue #5 already exists, comment there to get assigned.
