### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [multiverseweb/Dataverse#115]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@multiverseweb Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by SaanyaGarg5** [comment]
you can assign me this task...

**Comment by tarunkumar2005** [comment]
> you can assign me this task...

I am working on this

**Comment by tarunkumar2005** [comment]
@jency1 I am done creating the page but i was trying to add navbar and footer in that page also but the styles of the navbar and footer are very overriding directly applied to tags and all so do you want me to work on that also it will be bit difficult so hardcode everything but i will do it if you want just tell me asp i am working on it right now.

**Comment by tarunkumar2005** [comment]
![image](https://github.com/user-attachments/assets/e6913684-57bf-486b-87fd-4fe99792e51b)

Demo of the page @jency1 @multiverseweb

**Comment by multiverseweb** [comment]
@tarunkumar2005 hey, yes it would be nice if the style of this page and navbar match with the overall aesthetics of the website. I'll increase the level for this contribution,. Good luck!

**Comment by tarunkumar2005** [comment]
@multiverseweb I can't copy the navbar and footer on this page of contributor because there is so much of issue with the script.js file i have the same thing copied all the elements and used same script.js file in both the pages index.html and contributor.html but the hamburger is opening and closing on the index.html but not on contributor.html and saying .style.opacity is not accessible something like that how can this happen with same script.js if you can help me with that then i can do something otherwise i can create the PR with this design and functionality only if you had react js then we could have used the components but it is i can't figure out what is happning.

**Comment by multiverseweb** [comment]
@tarunkumar2005 okay, create a PR with the same design. I'll add the navbar. Just make sure to remove the irrelevant info from this page as you can see in the screenshots above `pencraft`, etc. Also, the page should be responsive.

**Comment by tarunkumar2005** [comment]
@multiverseweb I will do that the PR will not have these issues.
