### ISSUE TITLE
Adjusting the Footer of website as it looks kind of odd.

### ISSUE THREAD

**Issue by Vipul-Ydv** [multiverseweb/Dataverse#117]
Adjusting the Footer of website as it looks kind of odd. Will be adjusting the size spacing and maybe add some more features according to the need.

**Comment by Vipul-Ydv** [comment]
Do add labels

**Comment by jency1** [comment]
@Vipul-Ydv Share some images what you will be implementing. What is the current behavior and what will be the expected behavior.
