### ISSUE TITLE
enhancement of alignment of the text with the photo

### ISSUE THREAD

**Issue by Janmejai24** [multiverseweb/Dataverse#121]
The text and image of analysis on this page appear to be misaligned, which affects the visual presentation and user experience. The text is not aligned with picture of analysis . so they both can be aligned adjacent to each other which will enhance user experience. This misalignment disrupts the overall design of the page, and addressing it would improve the readability and aesthetics for visitors.
Please assign this issue to me under gssoc-extd and hacktoberfest
![image](https://github.com/user-attachments/assets/0af9d0b5-c79f-4bbf-af31-b6245e953c64)
![image](https://github.com/user-attachments/assets/72d3f8df-6a69-4503-80ce-9343f5c2d874)

**Comment by multiverseweb** [comment]
@Janmejai24 sure, go ahead!
