### ISSUE TITLE
Issue:  Alignment Problems in feedback section 

### ISSUE THREAD

**Issue by shantanumangalkar** [multiverseweb/Dataverse#127]
Issue:  Alignment Problems in feedback section 
The alignment of the Contact section affecting the overall visual appeal.

### Current Behaviour

- the alignment of the feedback section  it to extreme left  

### Expected Behaviour

- adjust the alignment to right so that it look properly aligned

### Screenshot
![Screenshot 2024-10-13 151114](https://github.com/user-attachments/assets/23e1a927-24b8-41e5-9ccf-fc22cd589454)

### Proposed Solution
- fixing the alignment of the feedback section 

### Technical Details
- fixing the css 

@multiverseweb Assign this to me under gssoc 2024 ext and hacktoberfest i would like to work on this isssue.

**Comment by multiverseweb** [comment]
Hey @shantanumangalkar, the issue belongs to [this project](https://github.com/multiverseweb/CodeIt).
