### ISSUE TITLE
Field issue in Form section

### ISSUE THREAD

**Issue by VidhanThakur09** [multiverseweb/Dataverse#13]
### **Description**

The current styling of the form requires improvement as placeholders are sticking toward the left section. This must be fixed so that the forms are properly presented when the user fills in their details in the forms.

![Screenshot 2024-10-02 003344](https://github.com/user-attachments/assets/ac77ee03-edd2-4c28-a6c2-81967892e5a8)

### Tasks:
Redesign the Form Section for better visual appeal.
Ensure that the placeholder doesn't stick towards the left section.

@Tejas-Gupta-7 can you assign this issue to me

**Comment by multiverseweb** [comment]
@VidhanThakur09 sure, go ahead!

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me.
