### ISSUE TITLE
Top Button Not Visible and Not Working in Last Two Sections

### ISSUE THREAD

**Issue by Sanikaaher-19** [multiverseweb/Dataverse#132]
Summary: The top button is not visible and is non-functional in the last two sections of the webpage. This issue affects user navigation and overall experience.

Details:

Visibility: The top button is not displayed properly in the last two sections of the page, making it difficult for users to access it.
![top button not visible](https://github.com/user-attachments/assets/da755f7f-96ab-40f4-85a7-b2fb8c5c91d6)

Affected Sections: The issue occurs specifically in the last two sections of the webpage, which may hinder users from easily returning to the top of the page.
![top button 2](https://github.com/user-attachments/assets/4b501628-5867-444e-975d-4af1a6ec8ac6)

Expected Behavior: The top button should be clearly visible and functional, allowing users to easily return to the top of the page from any section.

**Comment by Sanikaaher-19** [comment]
@multiverseweb
Please Review -Top Button Not Visible and Not Working in Last Two Sections

**Comment by multiverseweb** [comment]
Hey @Sanikaaher-19, similar issue #120 already exists, comment there to get assigned.
