### ISSUE TITLE
UPDATION IN README FILE REQUIRED

### ISSUE THREAD

**Issue by soham0028** [multiverseweb/Dataverse#135]
Hello @multiverseweb 

the current readme file lacks proper structure and does not contain the following :

-featured in section
-table of contents
-contributors 
-forkers and stargazers section
-back to top button

kindly assign me the issue under gssoc-extd and hacktoberfest labels so my work counts under these events
Thankyou .

**Comment by multiverseweb** [comment]
@soham0028 the current readme file already contains
- featured in section
- table of contents
- contributors
- back to top button

What motivated you to raise this issue?
