### ISSUE TITLE
DOESN'T REMAIN ON SAME MODE

### ISSUE THREAD

**Issue by ChauhanAyush04** [multiverseweb/Dataverse#14]
After refreshing it doesn't remain on dark/white mode which we have choose before refreshing.
![Screenshot 2024-10-02 013741](https://github.com/user-attachments/assets/9f5ceba5-1bc4-4d64-8038-1283c390b5ff)

**Comment by multiverseweb** [comment]
@ChauhanAyush04 can you solve this issue?

**Comment by ChauhanAyush04** [comment]
ok. i will solve it. assign me @multiverseweb

**Comment by multiverseweb** [comment]
@ChauhanAyush04 Assigned, Good luck!

**Comment by ChauhanAyush04** [comment]
@multiverseweb i have solved the issue. check the pull request
