### ISSUE TITLE
View password feature in login page and signup page

### ISSUE THREAD

**Issue by Preethii-R** [multiverseweb/Dataverse#144]
**_I noticed that the sign-up form currently lacks a "view password" option, which could lead to user errors. I would like to take on the task of implementing this feature to enhance user experience. Please let me know if I can proceed with this improvement._**

![Screenshot 2024-10-15 121013](https://github.com/user-attachments/assets/41318705-0314-4fce-a711-3dacfdce51ef)

![Screenshot 2024-10-15 121102](https://github.com/user-attachments/assets/641b6689-aeec-4a18-9bb5-b318ef64d3e9)

I am confident that resolving these issues will improve the page's usability and overall aesthetic. Please let me know if I can take on this task and contribute to improving the website.

**Comment by akilesh26** [comment]
Hi, I would like to work on this issue.

**Comment by multiverseweb** [comment]
@akilesh26 the issue has been assigned already.

**Comment by multiverseweb** [comment]
Hey @Preethii-R, are you working on this issue or shall we assign it to other contributors?

**Comment by jency1** [comment]
@Preethii-R I think you are not working on this issue, so I am assigning this issue to other contributors.
