### ISSUE TITLE
UI Improvements Needed for Dataverse Website

### ISSUE THREAD

**Issue by sanchitc05** [multiverseweb/Dataverse#145]
The current UI of the Dataverse website has a few noticeable issues that impact user experience and design clarity. Here's a summary of the key points:

**Website Name Not Visible:**

The branding or name of the website is not visible on the landing page, which diminishes the identity and recognition of the platform. It should be prominently displayed.

**Blank Screen on Scroll:**

When scrolling down the website, it turns into a black screen with no content or indicators, making it unclear whether there’s more information below or if the page has ended.

**Missing Seek Button:**

The website is missing a "seek" or navigation button that would help users quickly navigate to various sections or important features of the website. Adding a seek button would enhance usability, especially for first-time visitors.

**Suggestions for Improvement:**

_Enhance the Header:_ Ensure that the website name or logo is visible in the header or somewhere on the front view so that users can easily identify the platform.

_Content Below the Fold:_ Add meaningful content or visual cues when scrolling down so that the user is not faced with a blank screen.

_Add Seek Button:_ A seek or navigation button to jump between sections or back to the top could improve the navigation and user experience.

Please assign this issue to me.

**_Screenshot for Reference:_**

A screenshot highlighting the issues is attached.

![Screenshot (225)](https://github.com/user-attachments/assets/7050e726-97a4-4b92-988d-ef5ff7a57044)

**Comment by multiverseweb** [comment]
Hey @sanchitc05, I haven't seen this issue on any other device:
![IMG_20241016_234031](https://github.com/user-attachments/assets/46f34aef-f6ab-460f-9ca9-edbb17dc16d7)

Is that what you're seeing in all devices and browsers?

Coming to the issues you have mentioned, 
- The website name `Dataverse` is mentioned on the landing page and logo is on the top-left corner continuously.

- Can you share the screen recording of the `blank screen`? It maybe due to the fade-in effect of contents from the bottom.

- The seek button sounds interesting, I would like to see pictures of the ideas you have. Still, do you the website is long enough that it requires navigation through buttons? As there are only three sections on the home page.

These are just my perspective, looking forward to your response!
Thanks.

**Comment by sanchitc05** [comment]
@multiverseweb Hi, I ran it on my phone as well. It is performing well there and the DataVerse is clear and readable. But on my PC it's like that only. The screenshot is referred to above. Also, I have been a normal visitor to the site and felt the need for the seek button. I don't know it just keeps me informed about how long I have scrolled down a website and also I use seek buttons a lot! I don't scroll with the mouse's hover wheel instead I like to pinch down the seek button to quickly skip to the main content of the website for which I visited it. It's a psychological fact and most people have the same habit. That's my opinion, I would love to hear from your side.

**Comment by multiverseweb** [comment]
Okay sure @sanchitc05, but I would first like to see how the `seek button` actually looks like. Couldn't find it on the internet 😅

**Comment by sanchitc05** [comment]
@multiverseweb Sure let me add the screenshot to show what kind of seek button I am talking about.

![Screenshot (255)](https://github.com/user-attachments/assets/a960ca44-f313-44ec-8ceb-6f99c9d1d5ee)

See the rectangular box-type thing on the left side of the page. You might also be using it to scroll through the web pages when you don't feel like rotating the mouse wheel (as it scrolls at a very slow speed).

![Screenshot (256)](https://github.com/user-attachments/assets/7ec9d349-c061-46c7-8421-e1091fafdb6f)

That rectangular box or I may say the seek button is missing on the DataVerse website and I am planning to add that to it.

I hope you understand what I am saying. If you have any doubts, feel free to ask me.
