### ISSUE TITLE
Dataverse code build issues

### ISSUE THREAD

**Issue by Srijani-M** [multiverseweb/Dataverse#148]
### Current Behaviour

- Errors while running the code

### Expected Behaviour

- Code build should run successfully

### Screenshot

![codebuilterror](https://github.com/user-attachments/assets/18713a82-b13e-4fd0-8561-5d6f298fecdd)

### Technical Details

run code from PyCharm Community

**Comment by multiverseweb** [comment]
@Srijani-M I think removing `"C:\Users\msijj\Dataverse"` from the path will fix the errors. Make sure all paths are relative to folders and independent of the user's device.

**Comment by Srijani-M** [comment]
Thank you for the updates and I will try it.

**Comment by Srijani-M** [comment]
The above and few other build and run issues were resolved. However, ended up with below database issue. Looks like the "finance" database is referring to your localhost where this database is not available in my sys. Refer screenshot. Pls provide the finance db schema along with data so that I can run in my local to setup Db Or server host details with username and pwd where this database is hosted.
![MySQLConnectionIssue_gssoc24](https://github.com/user-attachments/assets/8a46112d-95a3-4788-9bd9-8421df0518c2)

**Comment by multiverseweb** [comment]
@Srijani-M well that's not as issue. In the details related to [Deployment Specifications](https://github.com/multiverseweb/Dataverse?tab=readme-ov-file#prerequisites) we have mentioned that the user will have to create the database first.
We will automate this process when the software is ready.

**Comment by Srijani-M** [comment]
Thanks for the response
I have successfully created database "Finance" in my local mysql.However
table scripts and data in tables are not mentioned in Deployment
Specifications.Please suggest.

**Comment by multiverseweb** [comment]
@Srijani-M, you just need to set the credentials like `host, user, passwd`, etc. [here](https://github.com/multiverseweb/Dataverse/blob/main/software/financeTracker.py#L17).
The required table creation will be handled by [this piece of code](https://github.com/multiverseweb/Dataverse/blob/main/software/main.py#L21-L26).
