### ISSUE TITLE
the code of conduct page appear blank first and it is confusing.

### ISSUE THREAD

**Issue by Sandigupta** [multiverseweb/Dataverse#152]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

Right now, when you open the code of conduct section, it appears blank at first. However, as you scroll down, the code of conduct begins to appear. Let me make it better. so that the content starts to appear.

### Proposed Solution

- Describe the feature or enhancement you'd like to see implemented.

### Screenshot/Mockup (Optional)
![screencapture-multiverse-dataverse-netlify-app-website-codeofconduct-2024-10-16-11_48_22](https://github.com/user-attachments/assets/f096dcf9-afbd-483a-bd05-be27f3cbc190)

- Attach any relevant visuals or mockups that illustrate your idea.

### Alternatives Considered

- List any alternative solutions or features you’ve considered before suggesting this one.

### Additional Context

- Include any extra details, links, or documents that can help clarify or support your feature request.

### Requirement/Document

- Share any document that outlines or supports this feature request.

**Comment by jency1** [comment]
@Sandigupta I have not found this type of error. You should check it once again.

**Comment by Sandigupta** [comment]
@jency1 
Currently, there is no problem.
