### ISSUE TITLE
 background can be added in front page (login part) 

### ISSUE THREAD

**Issue by shruti9935** [multiverseweb/Dataverse#154]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

- Describe the current situation or problem you're facing. Be specific about what’s lacking or what can be improved.

### Proposed Solution

- Describe the feature or enhancement you'd like to see implemented.

### Screenshot/Mockup (Optional)

- Attach any relevant visuals or mockups that illustrate your idea.

### Alternatives Considered

- List any alternative solutions or features you’ve considered before suggesting this one.

### Additional Context

- Include any extra details, links, or documents that can help clarify or support your feature request.

### Requirement/Document

- Share any document that outlines or supports this feature request.

**Comment by multiverseweb** [comment]
@shruti9935 the login and signup pages are already being re-designed under #237, so I'll be closing this issue.
