### ISSUE TITLE
for login we can add at the top at header

### ISSUE THREAD

**Issue by shruti9935** [multiverseweb/Dataverse#155]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

- Describe the current situation or problem you're facing. Be specific about what’s lacking or what can be improved.

### Proposed Solution

- Describe the feature or enhancement you'd like to see implemented.

### Screenshot/Mockup (Optional)

- Attach any relevant visuals or mockups that illustrate your idea.

### Alternatives Considered

- List any alternative solutions or features you’ve considered before suggesting this one.

### Additional Context

- Include any extra details, links, or documents that can help clarify or support your feature request.

### Requirement/Document

- Share any document that outlines or supports this feature request.

**Comment by jency1** [comment]
@shruti9935  You have not provided any description, provide relevant description and attach appropriate screenshots.

**Comment by multiverseweb** [comment]
@shruti9935 #237 fixes this. You should read the existing issues and PRs to avoid raising duplicate ones. This will help you save time and make useful efforts. Good luck!
