### ISSUE TITLE
Fix 'Get Dataverse' Button's hover effect.

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#16]
Fix the color of `Get Dataverse` Button in both dark mode and light mode.
- On hovering in dark mode, the font color should be black and background color should be white.
- On hovering in light mode, the font color should be white and background color should be black.

![image](https://github.com/user-attachments/assets/2c2f3e7a-f80c-4c5c-9cda-e52518b606e4)

**Comment by harish08102004** [comment]
Hey @multiverseweb I can work on this.

**Comment by multiverseweb** [comment]
@harish08102004 Okay, assigning.

**Comment by Kunj05** [comment]
@multiverseweb  can i work on this ?

**Comment by multiverseweb** [comment]
@Kunj05 , I have already assigned this issue. You can check out other issues that have not yet been assigned.

**Comment by harish08102004** [comment]
Hey @multiverseweb I have raised the PR please review it and merge.
