### ISSUE TITLE
Visualizing Demographic Data and Fatalities with Streamlit

### ISSUE THREAD

**Issue by greeshma275** [multiverseweb/Dataverse#162]
Title: Visualizing Demographic Data and Fatilities with Streamlit

I would like to add this tool to the project.
This tool creates an interactive web app using Streamlit to visualize demographic data and fatalities across various districts. It loads a dataset containing information on age, gender, citizenship, and event fatalities, then presents the data in multiple forms:

A histogram displaying the age distribution.
A dynamic bar chart that allows users to filter gender categories and view gender distribution.
A pie chart showing the distribution of citizenship.
An interactive map using Folium that visualizes fatality counts across districts, with markers and color-coded circles to represent the severity of fatalities.
This tool provides a detailed and visual understanding of the dataset, making complex data more accessible and insightful for users.

**Comment by jency1** [comment]
@greeshma275 Attach relevant screenshots of before and after implementing the changes.

**Comment by greeshma275** [comment]
![algo](https://github.com/user-attachments/assets/a00ac0ed-68d4-4b0a-b29c-05a115f5902c)

**Comment by multiverseweb** [comment]
@greeshma275 the tool you are proposing is useful but matches a little with the idea of Dataverse. Also, I don't have expertise in `Streamlit` and that technology is also not mentioned in the tech-stack for this project. This will create problems in testing and future contributions. Thanks for the idea, but I'll be closing this issue.

Good luck!
