### ISSUE TITLE
Login page and Sign up page not properly aligned and designed.

### ISSUE THREAD

**Issue by MimanshaKaur** [multiverseweb/Dataverse#164]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

1) Login and sign up pages do not have properly centered aligned form.
2) Login and sign up page have no background.
3) NO proper title names for both the pages.

### Expected Behaviour

1) i am thinking of redesigning its login and sign up page which will have properly centered aligned form.
2) a login and sign up page with beautiful theme based background.
3) proper title name

### Screenshot

![Screenshot 2024-10-17 003321](https://github.com/user-attachments/assets/482c3728-2e78-4672-a55b-853d9511ec1b)

### Proposed Solution

- i have to make changes in html and CSS files.

I will be happy to work on this issue. kindly assign me with gssoc-ext and hactoberfest-accepted labels.
@multiverseweb

**Comment by MimanshaKaur** [comment]
@multiverseweb kindly assign this take to me with gssoc-ext and hacktoberfest-accepted labels.

**Comment by multiverseweb** [comment]
Sure @MimanshaKaur, assigned. Make sure the design matches with the main website.

**Comment by MimanshaKaur** [comment]
@multiverseweb see i am done with both these pages....
LOGIN PAGE: 

![Screenshot 2024-10-23 011018](https://github.com/user-attachments/assets/6b5ba488-8be9-46d3-9776-558cafd2fc07)

SIGN UP PAGE:

![Screenshot 2024-10-23 011031](https://github.com/user-attachments/assets/5625ad96-32be-4f5d-9f87-89b199c3d187)


- i have redesigned everything...
- as page's load time was increased so i compressed the bg images and then used it 
- added logo and your website's name too.
- set all the form alignment.

that's why it took little much time..

hope you find it good too👍
kindly let me know if you want any changes in it and then finalize it  so that i can put PR.

**Comment by MimanshaKaur** [comment]
can i get level 3 label for this?😁😅😅..you have assigned 2 similar issues with level 3...

**Comment by MimanshaKaur** [comment]
@multiverseweb ???

**Comment by multiverseweb** [comment]
> can i get level 3 label for this?😁😅😅..you have assigned 2 similar issues with level 3...

Sure, you can. That's a lot of work you have done.
