### ISSUE TITLE
Updation Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [multiverseweb/Dataverse#165]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The contributing.md looks empty and not in a structured manner.

### Proposed Solution

I can update it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

**Comment by jency1** [comment]
@milansamuel609  Describe what sections will you add and attach relevant screenshots of it.

**Comment by milansamuel609** [comment]
I wanted to do these changes :-

Creating a good overall structure.
Adding a project structure section
Updating the pull request section
Adding alternate way of contributing through GitHub desktop section
Adding help and support section
Adding good coding practices section
Updating the issue report process section

![Screenshot 2024-10-18 013856](https://github.com/user-attachments/assets/3f0dab10-a21a-4b38-b4e6-2b4ad4c04933)

![Screenshot 2024-10-18 013933](https://github.com/user-attachments/assets/d79f7d3f-bf5a-4adf-a1f0-ecf014984557)

**Comment by multiverseweb** [comment]
Hey @milansamuel609, I think the structure of the existing [Contributing.md](Contributing.md) file is fine but it lacks `project structure section`. I'm assigning it to you. 
Feel free to reach out to us if you have any doubts.

**Comment by milansamuel609** [comment]
> Hey @milansamuel609, I think the structure of the existing [Contributing.md](Contributing.md) file is fine but it lacks `project structure section`. I'm assigning it to you. Feel free to reach out to us if you have any doubts.

Sure I will resolve that and thank so much for this opportunity.
