### ISSUE TITLE
design of scroll

### ISSUE THREAD

**Issue by ChauhanAyush04** [multiverseweb/Dataverse#17]
I think it would look good if we use full column in up and down scroll, instead of leaving space for two lines at end of scroll column.
![Screenshot 2024-10-02 014433](https://github.com/user-attachments/assets/742ae526-8d43-4709-9958-c12002319af7)

**Comment by multiverseweb** [comment]
@ChauhanAyush04 this website is not a part Dataverse. It has a separate repository. (not under GSSoC and Hacktoberfest)
