### ISSUE TITLE
Footer content - dark colors

### ISSUE THREAD

**Issue by saumyayadav25** [multiverseweb/Dataverse#170]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour
Currently the footer has text with darker color which does'nt look good.

### Expected Behaviour
Bright/light colors should be used

### Screenshot

<img width="1411" alt="Screenshot 2024-10-17 at 8 01 43 PM" src="https://github.com/user-attachments/assets/f5780fa8-8764-49af-9394-669c15e054b3">

### Proposed Solution
Bright colors or lighter shade of grey should be used in footer for better visibility.

**Comment by RajukrRaja** [comment]
@saumyayadav25 can i do this
