### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by JagritiChopra** [multiverseweb/Dataverse#173]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

- Describe the current situation or problem you're facing. Be specific about what’s lacking or what can be improved.

Most of the elements lacks hovering effect.

### Proposed Solution

- Describe the feature or enhancement you'd like to see implemented.
i wish to fix this. 

### Screenshot/Mockup (Optional)

- Attach any relevant visuals or mockups that illustrate your idea.
- 

### Alternatives Considered

- List any alternative solutions or features you’ve considered before suggesting this one.

### Additional Context

- Include any extra details, links, or documents that can help clarify or support your feature request.
Can you pls assign this to me under gssoc tag?

### Requirement/Document

- Share any document that outlines or supports this feature request.

**Comment by AK261102** [comment]
please assign me this task
