### ISSUE TITLE
Add Data Visualization in Financial Tracker

### ISSUE THREAD

**Issue by Kritika75** [multiverseweb/Dataverse#174]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The finance tracker provides basic tracking of expenses, income, and savings, but it has significant limitations in data visualization and analysis such as lack of Monthly Comparison, absence of Predictive Features and no Visualization of Expense Categories

### Proposed Solution

Implement monthly comparison charts to allow users to visually compare expenditure, income, and savings trends. Introduce predictive analytics that forecasts future spending and savings based on historical data, using models like linear regression. Additionally, add pie or bar charts to visualize spending by category (e.g., food, rent, entertainment). These enhancements will provide users with deeper insights into their financial situation, enabling better budget management.

### Alternatives Considered

Initially, I considered implementing basic tabular reports in Python using libraries like Pandas to present financial data. However, this approach lacks the visual impact of charts created with Matplotlib or Seaborn. I also thought about generating static PDF reports using ReportLab, but they wouldn't offer interactive insights

@multiverseweb Can you assign me this under Gssoc'24 ext?

**Comment by multiverseweb** [comment]
Hey @Kritika75, actually `visualizing expenditure by category (e.g., food, rent, entertainment)` is a bit complex as we'll have to take corresponding inputs from the user mandatorily as the software uses MySQL. Also, users won't be interested in such micro-management of finance on this software.

However, I liked the idea of `Predictive Analytics` and `Monthly Comparison Charts`. You can work on the same.
Reach out to me if you need help understanding the code.

The `static PDF report` feature is being developed under issue #5 .
Good luck!
