### ISSUE TITLE
Redesigned and Responsive Login/Sign-Up Page 

### ISSUE THREAD

**Issue by sagar27sahu** [multiverseweb/Dataverse#177]
### Current Behaviour

The current login and sign-up page UI lacks visual appeal and usability. The layout is basic, and the input fields, buttons, and text are not styled effectively. This impacts user experience, making it feel outdated and less engaging. Additionally, the links for "Sign Up" and "Forget Password" are not easily noticeable, and the page lacks responsiveness for mobile and smaller screens.

### Proposed Solution
I suggest redesigning the login and sign-up page with a more modern, visually appealing interface. The following enhancements should be made:
Improve layout and alignment of input fields and buttons.
Enhance button styling, adding hover effects and making them more prominent.
Create distinct and noticeable links for "Sign Up" and "Forget Password."

### Screenshot/Mockup (Optional)

<img width="1710" alt="Screenshot 2024-10-18 at 7 19 06 PM" src="https://github.com/user-attachments/assets/11cab05e-2c74-46e5-b14e-e47861025d13">

### Alternatives Considered
Initially considered retaining the current UI with minor tweaks such as bolding text, adjusting button sizes, and adding color to the links. However, this approach doesn't address the need for a comprehensive enhancement of the user interface. A full redesign is required to create a modern, user-friendly, and responsive experience that aligns with current web standards and best practices.

### Additional Context
These changes will improve user satisfaction and engagement with the platform. A fresh, modern design will also create a better first impression for new users during sign-up.

### Requirement/Document

There may be some front-end development requirements for implementing the new design (HTML/CSS/JavaScript). Additionally, if the platform has branding guidelines, the new design should align with those guidelines.

I am a gssoc-ext and hacktoberfest   contributor

**Comment by multiverseweb** [comment]
Sure @sagar27sahu, assigned. Please make sure the design of this page matches with the main website.

**Comment by multiverseweb** [comment]
@sagar27sahu similar issue #164 already exists and has been assigned. PR will be merged on first come first serve basis.

**Comment by sagar27sahu** [comment]
Ok

**Comment by sagar27sahu** [comment]
hi,@multiverseweb   i have completed the work and raised the pull request regarding it.please check.
