### ISSUE TITLE
Light mode bug

### ISSUE THREAD

**Issue by CharVaibhav** [multiverseweb/Dataverse#178]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

Hello there, as i was going through your website i found a bug a where i switched the website from dark mode to light mode i noticed that the footer part of the landing page doesnt change and still continues to remain in dark mode as mention bellow.

![Screenshot 2024-10-18 195118](https://github.com/user-attachments/assets/e4b76221-0ccb-48d5-a2ac-a0459a5186e4)

### Expected Behaviour

- I figured out how to solve this and this how it would look after redesigning, it sinks perfectly with the sync and flow of the website.

![Screenshot 2024-10-18 195201](https://github.com/user-attachments/assets/2b957395-e3c3-453f-ba2c-07d7b13dd4e2)

### Proposed Solution

1. Inspect HTML: Use browser developer tools to confirm the light-mode class is correctly applied to the div.

2. Check CSS Specificity: Ensure no other styles are overriding light-mode. Use more specific selectors if needed.

3. Verify JavaScript (if toggling): Ensure your JS correctly adds/removes the light-mode class.

4. Check CSS Loading: Confirm the CSS file is linked properly and paths are correct.

5. Test Across Scenarios: Ensure the styles apply consistently without interference from other elements or libraries.

**This streamlined process should help you quickly identify and fix the issue.**

**Comment by multiverseweb** [comment]
Hey @CharVaibhav, the issue has been resolved already. You can check it out [here](https://multiverse-dataverse.netlify.app/).
