### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [multiverseweb/Dataverse#179]
I want to add a page to showcase all the contributors of this website . 
@multiverseweb can you assign me this issue.

**Comment by multiverseweb** [comment]
Hey @T-Rahul-prabhu-38, the [contributors page](https://multiverse-dataverse.netlify.app/website/contributor) already exists on the website footer. 
Kindly check the website as well as PRs thoroughly before raising issues. : )
