### ISSUE TITLE
Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [multiverseweb/Dataverse#180]
I want to add multi language support system to the website which can help us understand in their native language.
@multiverseweb can you assign me this issue.

**Comment by multiverseweb** [comment]
Hey @T-Rahul-prabhu-38, nowadays most of the web browsers offer this translation feature. So, I don't think we need to add this feature ourself.
Here is a relevant screenshot:
![image](https://github.com/user-attachments/assets/9c420baa-e8d5-4dcb-bab7-ecd1afd1d000)
