### ISSUE TITLE
Adding Translation Tool

### ISSUE THREAD

**Issue by VidhanThakur09** [multiverseweb/Dataverse#181]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour
The current language of the website is English which make the website not accessible to people from diverse linguistic backgrounds. 

![Screenshot 2024-10-19 013935](https://github.com/user-attachments/assets/75e9bd14-5af1-4be5-9e2b-f7fbaaaeef02)

### Proposed Solution

Adding a translation tool to your website can offer numerous benefits, from expanding your global reach to improving user experience and boosting SEO.

- designing the Translation Tool for better visual appeal.
- Improving the styling of Translation Tool .

### Screenshot/Mockup (Optional)

https://github.com/user-attachments/assets/8ab62069-13fe-4915-9341-60fdb42b81e6

### Additional Context

@multiverseweb  can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by multiverseweb** [comment]
Hey @VidhanThakur09, nowadays most of the web browsers offer this translation feature. So, I don't think we need to add this feature ourself.
Here is a relevant screenshot:
![image](https://github.com/user-attachments/assets/9c420baa-e8d5-4dcb-bab7-ecd1afd1d000)

**Comment by VidhanThakur09** [comment]
Thank you for sharing the information.
