### ISSUE TITLE
improve the footer alignment & UI 

### ISSUE THREAD

**Issue by jayanththalla** [multiverseweb/Dataverse#188]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The page the at the copy right and the let me know thoughts and the footer must be improve 

### Proposed Solution

The copy right is at the bottom of the page and the icon and the title with description at left and right side should be components

### Screenshot/Mockup (Optional)

![image](https://github.com/user-attachments/assets/906a5976-1fe7-4c88-8301-3a5878f71d08)

### Additional Context

please assign me @pa

**Comment by jency1** [comment]
@jayanththalla  What will you change ? How will it look like after the changes ? Provide relevant images.
