### ISSUE TITLE
Issues and Improvements in Website JavaScript Code

### ISSUE THREAD

**Issue by Deeptig9138** [multiverseweb/Dataverse#19]
Incorrect navbar Selector
Use window.scrollY: Replace this.scrollY
Multiple Event Listeners: Consolidate redundant event listeners attached to contribute to improve performance.
Error Handling in addMarker Function: Add a check for data.length and handle errors when fetching city coordinates.

Please assign this to me @multiverseweb @Tejas-Gupta-7 
I am a gssoc contributor and hacktoberfest too

**Comment by multiverseweb** [comment]
@Deeptig9138 Sure, assigned. Don't forget to create a new branch `gssoc-yourName` before sending the PR.

**Comment by multiverseweb** [comment]
@Shalinis19137 sure, assigned.
