### ISSUE TITLE
 Rearranging Copyright Section on Website Layout

### ISSUE THREAD

**Issue by Vaibhavkum1321** [multiverseweb/Dataverse#191]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The website currently displays the copyright section directly above the links to other pages. This placement can lead to a cluttered appearance and may distract users from navigating the site effectively. The copyright notice can also be overlooked due to its positioning, reducing its visibility.

### Proposed Solution

I propose moving the copyright section to the bottom of the page. This adjustment will create a cleaner layout, allowing the links to other pages to take precedence. By positioning the copyright section at the bottom, it will be more consistent with standard website design practices and improve the overall user experience

### Screenshot/Mockup (Optional)

![image](https://github.com/user-attachments/assets/29dc87f0-b614-4e6c-88c0-22ab648b7e81)

### Alternatives Considered

- **Keeping the Current Layout:** No change to the copyright section's position, maintaining the status quo.
- **Redesigning the Copyright Section:** Making the copyright section more visually appealing without changing its position.
- **Collapsing the Copyright Section:** Allowing users to expand/collapse the copyright area, but this could complicate the interface.

### Additional Context

This change aligns with common web design practices, where the copyright information is typically found at the bottom of the page. It can help improve user engagement by reducing distractions and focusing attention on navigation links.

@multiverseweb Please review this enhancement and assign it to me , so i can start working on it...

**Comment by jency1** [comment]
@Vaibhavkum1321 Are you still working on this issue ?

**Comment by Vaibhavkum1321** [comment]
Yes sir
....i will fix this tonight

**Comment by Balamurugan-cyber** [comment]
please assign this issue

**Comment by Vaibhavkum1321** [comment]
Ok, I will do it.
