### ISSUE TITLE
Login/signup button alignment issue.

### ISSUE THREAD

**Issue by Zubaida0113** [multiverseweb/Dataverse#192]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

The login/sign up button is not aligned properly. It is overlapping with the hamburger when the website is open in laptop and in mobile screen the login/signup button is out of frame
![image](https://github.com/user-attachments/assets/4166846b-a2c4-4671-bf16-ec698c463f1a)
![Screenshot (472)](https://github.com/user-attachments/assets/c3c20b80-dcd2-448f-a381-28953fddb5d5)

### Expected Behaviour
I would like to work on its alignment issue, and I want to ask if I can make two different login and signup buttons.
Please tell me your thoughts regarding the above mentioned issue.

**Comment by Zubaida0113** [comment]
Hi @multiverseweb. Please look into the above issue and respond.

**Comment by multiverseweb** [comment]
The issue is already being resolved under #225.
