### ISSUE TITLE
Logo feature proposed

### ISSUE THREAD

**Issue by Zubaida0113** [multiverseweb/Dataverse#193]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour
The current dashboard looks cool but the top header looks a bit empty. 
![image](https://github.com/user-attachments/assets/66aa1447-9b8b-4124-a120-625622324047)

### Proposed Solution
So, I was wondering whether we can move the logo to the centre of the heading. 
I would be glad to work on this issue if you think it's a good suggestion.

I can work on the logo too if you want.

**Comment by multiverseweb** [comment]
Hey @Zubaida0113, one contributor is working on expanding the navbar horizontally for desktop view, so there is no need to center the logo.
Also, I couldn't understand what you meant by `I can work on the logo too if you want.`. Do you want to redesign the logo?

**Comment by multiverseweb** [comment]
I hope you can clarify the issue soon @Zubaida0113 

> Hey @Zubaida0113, one contributor is working on expanding the navbar horizontally for desktop view, so there is no need to center the logo. Also, I couldn't understand what you meant by `I can work on the logo too if you want.`. Do you want to redesign the logo?
