### ISSUE TITLE
Add navbar and footer to the encryptify page

### ISSUE THREAD

**Issue by SandhyaSankararaman** [multiverseweb/Dataverse#194]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The page for encryptify is currently designed to provide the functionality it offers. There is no way to navigate to other pages or a footer

### Proposed Solution

I would like add the navbar and the footer in the similar manner as in the home page. 

It would be great if you could assign it under gssoc-ext, hacktoberfest2024 along with the level labels. I will get it as soon as possible

**Comment by multiverseweb** [comment]
Hey @SandhyaSankararaman, actually 'Encryptify` is not a part of this project, it has a separate repsoitory which is not under gssoc-ext and hacktoberfest2024.
