### ISSUE TITLE
Home page header improvement

### ISSUE THREAD

**Issue by BhavaniSankar0107** [multiverseweb/Dataverse#195]
### Current Situation
The homepage header is looking sparse and incomplete, with only the "Login/Signup" option, leaving a significant empty space.
![image](https://github.com/user-attachments/assets/3ddf0783-c81b-4167-bb8e-87514a364a04)

### Proposed Solution
1. I want to add the "Dataverse" at the logo 
2. I want to bring out the pages "Figma Design" and "Encriptify" to the header also to make home page header look complete. 
3. I want to add space between "login/signup" option and menu option.

I would start working on this if you could assign it to me under gssoc-ext, hacktoberfest2024 and level labels.

**Comment by multiverseweb** [comment]
Sure @BhavaniSankar0107. 
1. You can add "Dataverse" at the logo, but make sure to hide it in mobile view.
2. We'll be removing "Figma Design" and "Encriptify" from the navbar soon as many more useful links are to be added, so let's not change this for now.
3. You can add space between "login/signup" option and menu option.

**Comment by BhavaniSankar0107** [comment]
I have completed the changes. This is how it looks like now:
![image](https://github.com/user-attachments/assets/85474547-0f53-4c14-8a3a-28daaec92306)

I have made a pull request with these changes.

**Comment by BhavaniSankar0107** [comment]
Please assign the necessary labels for the pull request
