### ISSUE TITLE
Enhancement of Header and Footer of website

### ISSUE THREAD

**Issue by aashutosh585** [multiverseweb/Dataverse#196]
hey @multiverseweb ,I found some improvement places in website.
**Current Behaviour**
The current header and footer of the website lack modern design elements, in header side login and sign up mix ,in footer side icon are not good in visiblity and do not provide an optimal user experience across different devices.

**Proposed Solution**
I propose enhancing the header and footer with modern UI/UX principles, making them more visually appealing and responsive. This could include improvements to layout, icons, and navigation elements, ensuring a seamless experience across mobile, tablet, and desktop devices.

Screenshot/Mockup (Optional)
![Screenshot 2024-10-20 204639](https://github.com/user-attachments/assets/66845d85-abc0-4d24-b906-16b46ac4d797)

assign me for this work :)
Please make sure to add labels gssoc-ext, hactoberfest, level1, level2, level3.

**Comment by multiverseweb** [comment]
Okay @aashutosh585, assigned. Make sure to maintain the simplicity and clean layout of the website (avoid animations) as the main focus of this website is to promote the software without much distractions.

**Comment by multiverseweb** [comment]
Also, just give me an idea of what changes you would like to make in the footer of the website?

**Comment by RajukrRaja** [comment]
@multiverseweb can i do this

**Comment by aashutosh585** [comment]
@multiverseweb you can check what change I have done in footer ,if you want something then tell me

**Comment by multiverseweb** [comment]
@aashutosh585 Can you mention the PR number here?
Or mention the issue number in your PR.

**Comment by aashutosh585** [comment]
hey @multiverseweb PR number is #224
