### ISSUE TITLE
Set the upper limit to 16 for colors

### ISSUE THREAD

**Issue by Rohan20-10** [multiverseweb/Dataverse#198]
@Rohan20-10 Yes 16. Do you know why I set the upper limit to 16?
It's just because in the list `colors`, I have added only 16 colors. We can increase that anytime. 
There is an effective thing we can do, we can set a variable `maxLimit` and set it to 16. We can use that variable everywhere in the program instead of the number `16`.
 The variable must be defined near the list `colors`.
What do you think?

If you're interested in this you can either raise a new issue or solve this in the same PR.

_Originally posted by @multiverseweb in https://github.com/multiverseweb/Dataverse/issues/4#issuecomment-2395446165_
@multiverseweb this issue was pending to work. Will you assign it to me?

**Comment by multiverseweb** [comment]
Sure, assigned.
