### ISSUE TITLE
Input Validation Issue: Name and Description Fields Ignored

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#2]
Feature Description:
The form currently allows users to submit without filling in the Name and Description fields. This leads to incomplete submissions, as only the Gmail field is being validated.

Use Case:
Users should be required to fill in all fields (Name, Gmail, Description) to ensure that complete information is collected before form submission.

Add Screenshots:
![Screenshot 2024-10-01 190851](https://github.com/user-attachments/assets/497617a0-c8d1-4f53-803d-b99d3afa42ac)

**Comment by lkksharma** [comment]
Hi @multiverseweb,
I am from GSSoc Ext '24 and I would like to contribute to this project. We can do this by making the fields required. Kindly assign it to me.

**Comment by Kunj05** [comment]
Hi @multiverseweb  do assign me this issue i can add proper validation

**Comment by multiverseweb** [comment]
@Kunj05 okay, go ahead.

**Comment by Roopalgn** [comment]
hey @multiverseweb can i work on this issue as well?

**Comment by SaiNivedh26** [comment]
I can definitely work on this @multiverseweb . Assign me up :)

**Comment by ruchikakengal** [comment]
I would like to give styling to form and fix the validation issue

**Comment by multiverseweb** [comment]
The issue has been resolved.
