### ISSUE TITLE
Issues in Tkinter and Matplotlib Code in Data Visualization

### ISSUE THREAD

**Issue by Deeptig9138** [multiverseweb/Dataverse#20]
Redundant Imports: import datetime is unnecessary as specific functions are already imported.
Global Variable: The global variable count should be defined inside the function.
Unclosed MySQL Connection: Add mycon.close() after data fetching to close the connection properly.
Mixed Input Methods: Avoid mixing Tkinter GUI inputs with command-line input(). Stick to one method, preferably Tkinter.
Repetitive Code: Refactor the plotting logic (plt.bar(), plt.hist(), etc.) into a helper function to avoid redundancy.

Please assign this to me @multiverseweb

**Comment by multiverseweb** [comment]
@Deeptig9138 Sure, Good luck! It's amazing that you pointed out minute bugs such as `mycon.close()`. Assigned it to you.

**Comment by multiverseweb** [comment]
@Deeptig9138 Don't forget to create a new branch `gssoc-yourName` before sending the PR.

**Comment by saniyaahemad12** [comment]
Please assign this to me @multiverseweb

**Comment by multiverseweb** [comment]
What changes would you like to make @saniyaahemad12 ?

**Comment by saniyaahemad12** [comment]
I have identified two simple and quick changes that can improve the current functionality of the data visualization tool:

Ensure Plot Updates with canvas.draw()
Currently, the plots may not update dynamically. By adding a canvas.draw() call after any plot modifications, we can ensure that the charts are refreshed and displayed correctly in the Tkinter window.

Clear Figures Before Redrawing
To avoid stacking multiple figures on top of each other when new data is plotted, I suggest clearing the current figure using fig.clear() before each plot update. This will prevent memory issues and ensure only the updated chart is visible.

These are easy to implement but will enhance the usability of the tool. Let me know if you'd like to proceed with these changes.

**Comment by multiverseweb** [comment]
@saniyaahemad12 hmm...much needed! Assigning it to you. Good luck!

**Comment by multiverseweb** [comment]
Hey @saniyaahemad12, any updates? Let me know if you need any help.

**Comment by saniyaahemad12** [comment]
sure @multiverseweb

**Comment by Rohan20-10** [comment]
@multiverseweb can I work on this issue?

**Comment by multiverseweb** [comment]
Sure @Rohan20-10, assigned.

**Comment by Rohan20-10** [comment]
> I have identified two simple and quick changes that can improve the current functionality of the data visualization tool:
> 
> Ensure Plot Updates with canvas.draw() Currently, the plots may not update dynamically. By adding a canvas.draw() call after any plot modifications, we can ensure that the charts are refreshed and displayed correctly in the Tkinter window.
> 
> Clear Figures Before Redrawing To avoid stacking multiple figures on top of each other when new data is plotted, I suggest clearing the current figure using fig.clear() before each plot update. This will prevent memory issues and ensure only the updated chart is visible.
> 
> These are easy to implement but will enhance the usability of the tool. Let me know if you'd like to proceed with these changes.

@multiverseweb please clarify the first requirement mentioned here by sending me a reference through a video. The second requirement I have understood so please clarify this so that I can make the changes together. Thanks.

**Comment by multiverseweb** [comment]
@Rohan20-10 as you can see in the video the graph didn't update in the same window, instead a new window popped up:

https://github.com/user-attachments/assets/583ee27b-b9dc-43c4-91eb-7b38e757376b

Expected behaviour is that the plots should update in the same window. I think this requirement is similar to the second one.

**Comment by Rohan20-10** [comment]
@multiverseweb have understood the issue and will fix it and revert to you asap. Thanks.
