### ISSUE TITLE
[Bug] Design issue: The Login button appears at the background of the Navigation menu icon at top right corner of the webpage.

### ISSUE THREAD

**Issue by NumlStudentSE** [multiverseweb/Dataverse#204]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

The Login button appears at the background of the Hamburger menu or Navigation menu. 

### Expected Behaviour

The Navigation menu icon should appear at the top right corner of the webpage. The Login button should appear alongside the Navigation menu icon.  

### Screenshot

![image](https://github.com/user-attachments/assets/e85386dd-53e0-45c6-9409-e987f095429b)

### Proposed Solution
The identified bug is a common design related issue. It must be solved by using the frontend language and apply the required styling to the Login button and Navigation menu icon.

### Severity:
Medium

### Steps to Reproduce:
1. Open the homepage.
2. Observe the top right corner of the webpage where the Login button and Navigation menu icon are located.

### Expected Result:
The Login button should be clearly visible and accessible without overlapping with other elements.

### Actual Result:
The Login button appears behind the Navigation menu icon.

### Technical Details
Moreover, as the login button appears on the background of the navigation menu icon so the user is unable to click on the Login button.

**Comment by NumlStudentSE** [comment]
Please review and accept the bug report @Tejas-Gupta-7

**Comment by multiverseweb** [comment]
@NumlStudentSE similar issue #171 already exists and has been assigned.
