### ISSUE TITLE
Enhancing Login/Signup Pages

### ISSUE THREAD

**Issue by Bhum-ika** [multiverseweb/Dataverse#208]
The current pages have 0 to no styling. I would like to give them a minimalist look.

![Screenshot 2024-10-21 145849](https://github.com/user-attachments/assets/fb7e1967-ef36-46e8-a330-4232b67f4903)
![Screenshot 2024-10-21 145855](https://github.com/user-attachments/assets/23051b03-81f9-469a-be2e-4027d8a2772c)

And also signUp form has no margin-bottom

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by multiverseweb** [comment]
Sure @Bhum-ika, assigned.

**Comment by multiverseweb** [comment]
@Bhum-ika make sure the design matches with the aesthetics of existing website.

**Comment by Bhum-ika** [comment]
For sure

**Comment by praneethaBrindavanam** [comment]
@multiverseweb  hey looks like the login/sign in pages are not opening [https://multiverse-dataverse.netlify.app/login.html](url)
i would like to ask you on this and assign !

**Comment by multiverseweb** [comment]
@praneethaBrindavanam create a new issue for it to get assigned.
