### ISSUE TITLE
Improving Footer UI and user feedback visibility

### ISSUE THREAD

**Issue by Ananya200305** [multiverseweb/Dataverse#211]
<img width="1326" alt="Screenshot 2024-10-12 at 1 42 19 PM" src="https://github.com/user-attachments/assets/989d78cf-276e-4aae-9ed4-5fface98de5b">

I came across the issue regarding the UI improvements for the footer and user feedback visibility. I would love to take ownership of this task and work on enhancing the usability and appearance of the elements mentioned. Please assign this to me under ggsoc-ext with appropriate level.

**Comment by multiverseweb** [comment]
@Ananya200305 The `footer has been fixed` by multiple smaller PRs, so I have closed the issue.
