### ISSUE TITLE
Enhanced Data Security for Finance Tracker

### ISSUE THREAD

**Issue by snehab03** [multiverseweb/Dataverse#222]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The current finance tracker stores passwords using encryption, but for sensitive financial data, adopting multi-layer security practices could be more robust.

### Proposed Solution

1. Implement hashing algorithms (e.g., bcrypt, Argon2) instead of simple encryption for password storage.
2. Integrate 2FA (Two-Factor Authentication) for user login to improve security.
3. Utilize SSL/TLS certificates to ensure secure data transmission.

**Comment by multiverseweb** [comment]
Hey @snehab03, just give me a brief of how you're going to implement the solutions you have proposed. Include the technologies you will use and the steps you'll follow.
This is just to make sure the contribution is relevant to the future features I'm planning to integrate in `Dataverse`.
