### ISSUE TITLE
I want to enhance the code of conduct section of the documentation

### ISSUE THREAD

**Issue by NumlStudentSE** [multiverseweb/Dataverse#223]
I want to add the following sections in the code of conduct section to reduce conflicts, enhance communication, and providing support to the open-source contributors. 
Purpose
Acceptable/Unaccpetable Behavior
Reporting Violations
Action against Violation
Information to Include
Enforcement guidelines
Scope
Guide for Beginner Contributor
Contact Information

Screenshot:
![image](https://github.com/user-attachments/assets/643c6f33-8fdf-432b-a212-f1eea57191fd)

![image](https://github.com/user-attachments/assets/988dddef-3421-4461-8fcc-b38e7b8ea3d9)

![image](https://github.com/user-attachments/assets/425774f7-d524-427c-a5a3-e403a98413a9)

![image](https://github.com/user-attachments/assets/d78dadad-4dd1-4795-842c-3617d9bec361)

Please assign this issue to me @Tejas-Gupta-7

**Comment by multiverseweb** [comment]
Hey @NumlStudentSE, I think the existing `code of conduct` is fine as it consists most of this information.
