### ISSUE TITLE
the login in button overlap the menu button

### ISSUE THREAD

**Issue by REHAN-18** [multiverseweb/Dataverse#233]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour
 the login/signup button overshadow the menu button

### Expected Behaviour
 they should align in corrected way

### Screenshot

<img width="1173" alt="Screenshot 2024-10-25 at 1 21 15 AM" src="https://github.com/user-attachments/assets/54cd305d-578d-43a9-aa34-40110d555020">

### Proposed Solution
 fix the css of this two button

**Comment by anandshukla15** [comment]
please @multiverseweb  assign this to me , it will be a great to work on this

**Comment by REHAN-18** [comment]
@multiverseweb assign me I raise the issue first !!1

**Comment by multiverseweb** [comment]
@REHAN-18 similar issues already exist and are being solved in ongoing PRs.
