### ISSUE TITLE
[Feat ] : Add Google Translator for Multi-language Support

### ISSUE THREAD

**Issue by Edasgh** [multiverseweb/Dataverse#235]
### Description
We need to integrate Google Translator into the multiverse web application to allow users to translate all pages into multiple languages. This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

•	Users should be able to translate any page to their selected language using the Google Translator integration.
•	The layout and styling of pages should not break when the content is translated.
•	The language selector should be accessible and functional on all pages.

Program: GSSOC-ext and hacktoberfest
** Please add LEVEL 3 to the issue**
Please assign me this issue
Thank You in advance  @multiverseweb

**Comment by multiverseweb** [comment]
Hey @Edasgh, similar issues have been closed because most of the browsers provide `translate` feature and the website by default opens in local language chosen by the user in browser settings. You can check issue #181.
