### ISSUE TITLE
adding hacktoberfest and gssoc banner to the readme file

### ISSUE THREAD

**Issue by agarwalbhargavi** [multiverseweb/Dataverse#236]
i would like to add hacktoberfest and gssoc banner to the readme file under the heading this project is officially accepted for.
@multiverseweb kindly assign me this

**Comment by multiverseweb** [comment]
Hey @agarwalbhargavi, I think banners are not required as this section provides the same information:
![image](https://github.com/user-attachments/assets/0c6a2436-ac16-45dd-970a-b2fbe1e0c9be)
