### ISSUE TITLE
Improve "Let Me Know Your Thoughts!" form in footer

### ISSUE THREAD

**Issue by himanshu-sheetlani** [multiverseweb/Dataverse#238]
### Current Behaviour

the current form looks a lot simpler, but it needs some improvement
![ice_screenshot_20241025-195636](https://github.com/user-attachments/assets/e974ece6-5963-43e2-86a3-a8b5c7e56d77)

### Expected Behaviour

Expected design
![ice_screenshot_20241025-223856](https://github.com/user-attachments/assets/d8a1c0e2-7fdd-4f20-ba6d-4dd8ac36efb4)

### Proposed Solution

Need to make a few changes in wesite/style.css and index.html file

### Technical Details

frontend enhancement

make this issue for Octoberfest and GSSOC-EX 2024

**Comment by multiverseweb** [comment]
Hey @himanshu-sheetlani, I think the current design is file as it matches with the aesthetics of the overall website.
