### ISSUE TITLE
Hey, the website is good and visually appealing. From the attractive processing icon to appealing pictures and the graphs. My suggestion is that we can also have the different style of the cursor (with unique style and color) which will add an extra appealing effect to the website.  

### ISSUE THREAD

**Issue by deepakchoudhary-dc** [multiverseweb/Dataverse#240]
Have an idea for a new feature? Please fill out the sections below. 😊

**Comment by multiverseweb** [comment]
Hey @deepakchoudhary-dc, thank you very much. Glad you liked the design of the website. 
I don't think adding a custom cursor is required as I want to keep the design simple and with less animations.
Thanks for the idea though.
Good luck!
