### ISSUE TITLE
Proposal to Introduce a Dedicated Navigation Bar,Enhance Navbar UI/UX for Improved User Experience

### ISSUE THREAD

**Issue by Ankul8471** [multiverseweb/Dataverse#242]
Current Behaviour
Currently, PathSphere lacks a dedicated navigation bar, making it challenging for users to find and access different sections of the platform. This absence can lead to confusion and increased time spent searching for essential features, resulting in a less intuitive user experience.

Proposed Solution
I propose implementing a dedicated navigation bar at the top of the application that includes key sections such as:

Home
About Us
Services
Contact
User Profile (if applicable)
Additional resources (like documentation or FAQs)
The navbar should feature a clean and modern design that aligns with PathSphere’s branding, incorporating intuitive icons alongside text for better visual recognition. It should also be fully responsive to ensure a seamless experience across all devices and include accessibility features like ARIA roles for inclusive navigation.

Screenshot/Mockup (Optional)
Currently, there are no visuals available, but I can create mockups for discussion.

Alternatives Considered
Relying on a sidebar menu: While a sidebar could organize content, it may take up valuable screen space and can become cumbersome on smaller devices.
Using dropdown menus: This can create a cluttered interface and may not provide immediate visibility for essential sections.
Additional Context
A dedicated navbar can significantly enhance user engagement by providing quick access to important features, reducing frustration, and making the overall user experience smoother. It would also contribute to a more professional appearance for the platform.

Requirement/Document
Currently, there are no supporting documents available, but user feedback can be collected to underscore the need for this feature.

![Screenshot 2024-10-26 223147](https://github.com/user-attachments/assets/303c0ed0-3772-4c4b-a1cb-1312f5aa6921)

**Comment by multiverseweb** [comment]
@Ankul8471 almost all of the features you have mentioned in this PR already exist in `Dataverse`. Looks like you have copied the issue from another project `PathSphere` and forgot to change the name.

Consider going through the project first and then raise relevant issues.

**Comment by Ankul8471** [comment]
Yes I seen same issue in this website and I forgot to change the name of website
