### ISSUE TITLE
Redesign Footer to Include Quick Links, Contact Information, and Accessibility Features

### ISSUE THREAD

**Issue by Ankul8471** [multiverseweb/Dataverse#243]
Current Behaviour
The current footer on PathSphere is minimalistic and lacks essential elements that could enhance user engagement and provide quick access to important information. Key sections such as "Contact Us," "Privacy Policy," "Terms of Service," and social media links are missing, making it harder for users to navigate or get in touch with the platform.

Proposed Solution
Introduce a well-designed footer with the following enhancements:

Information Sections:

Quick Links: Links to important pages like "About Us," "Services," "Privacy Policy," and "Terms of Service."
Contact Information: Display an email address, contact number, and possibly a feedback form for user inquiries.
Social Media Links: Icons that link to PathSphere’s social media profiles (e.g., LinkedIn, Twitter, Instagram), enhancing the platform’s online presence.
Design & Accessibility:

Adopt a clean, organized layout with a color scheme matching PathSphere's branding.
Ensure that the footer is fully responsive and visually appealing across all devices.
Include accessibility features like keyboard navigation and visible contrast for text.
Additional Functionalities:

Option for a newsletter signup to keep users updated.
"Back to Top" button for easy navigation on long pages.
Screenshot/Mockup (Optional)
Visuals can be provided if needed to demonstrate the proposed layout and design.

Alternatives Considered
Keeping the footer minimal to avoid clutter: While simplicity is valuable, including key information and links is crucial for accessibility and functionality.
Adding only a social media section: However, a complete footer with contact details and important links will better serve users’ needs.
Additional Context
A more comprehensive footer will improve PathSphere's usability and professionalism by providing users with clear, accessible information. This will also make the platform more approachable, fostering trust and engagement.

![Screenshot 2024-10-26 223923](https://github.com/user-attachments/assets/cf455159-cca0-47bf-bf7c-7ab8c96e7028)

**Comment by multiverseweb** [comment]
This issue has similar problems as #242.
