### ISSUE TITLE
Refactoring: Sign Up Page Redesigning

### ISSUE THREAD

**Issue by VanshGarg06** [multiverseweb/Dataverse#244]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

Sign Up page is taking less information as usual and the alignment of elements are also not having right margin and padding.

### Expected Behaviour

Alignment of the elements are not stable and even some more information could be taken.

### Screenshot

![image](https://github.com/user-attachments/assets/87d1539b-b571-41a4-ac80-e8127c5f6020)

### Proposed Solution

Redesigning of Sign Up page and aligning the elements as stable.

### Technical Details

Browser version: Google Chrome(130.0.6723.70,64-bit)
Node.js version :  V16.16.0
Please assign this issue to me @multiverseweb under hacktoberfest and gssoc-ext under level 2 necessary labels.
Please assign me @VanshGarg06 this issue as soon as possible.

**Comment by multiverseweb** [comment]
@VanshGarg06 The `SignUp` page is being re-designed under #237, these problems will be fixed there.
What `more information` do you think should be taken through this form?

**Comment by VanshGarg06** [comment]
The alignment and layout could be better of the sign up page.

**Comment by multiverseweb** [comment]
That counts in the design, so I'm closing this issue.
