### ISSUE TITLE
UI enhancement : Enhance  GET DIVERSE Button Design on Homepage

### ISSUE THREAD

**Issue by swati-204** [multiverseweb/Dataverse#247]
Enhance the appearance and interactivity of the button on the homepage to improve user engagement and overall design consistency.

![Video Screen1730005486649](https://github.com/user-attachments/assets/a474d389-5477-44ec-883d-456fa91cf3a3)

@juikalage Can you assign this to me? I would love to work on this

**Comment by swati-204** [comment]
There is an issue in the deployment links of both projects in the GSSOC project section. Clicking on the "CodeIt" link redirects to the "Dataverse" page, and vice versa. The links should direct users to the correct project pages.

**Comment by swati-204** [comment]
@multiverseweb  Also, I want to update the button using more enhancing features like Adding gradient colors or shadows for a modern, elevated look.
Use subtle hover and focus effects (like scaling, color shift, or shadow) for interactivity.
Update the border radius for a rounded or pill-shaped button if it fits the theme.

**Comment by multiverseweb** [comment]
> @multiverseweb There is an issue in the deployment links of both projects in the GSSOC project section. Clicking on the "CodeIt" link redirects to the "Dataverse" page, and vice versa. The links should direct users to the correct project pages.

Oh, I see.

**Comment by multiverseweb** [comment]
> @multiverseweb Also, I want to update the button using more enhancing features like Adding gradient colors or shadows for a modern, elevated look. Use subtle hover and focus effects (like scaling, color shift, or shadow) for interactivity. Update the border radius for a rounded or pill-shaped button if it fits the theme.

I will assign you the issue but just keep in mind that it is  a design-related issue, it is not necessary that the design that one person likes should also be liked by others. So I'll merge the PR if I liked the new design.

I would suggest you to retain the rectangular-shape as it matches with the software's design.
