### ISSUE TITLE
add feature in table in readme.md

### ISSUE THREAD

**Issue by ananyag309** [multiverseweb/Dataverse#25]
this will enhance the readme.md - kind of adding this table
![featured in](https://github.com/user-attachments/assets/fd50024a-9c78-44ad-bfb3-927065f8d802)

**Comment by rishikaa1** [comment]
@ananyag309 hi, i would like to work on this!

**Comment by multiverseweb** [comment]
Sure @ananyag309, assigned. Make sure to create a new branch `gssoc-yourName` before sending the PR.

**Comment by rishikaa1** [comment]
@multiverseweb thank you.
