### ISSUE TITLE
Code Optimization and Refactoring for `script.js`

### ISSUE THREAD

**Issue by smog-root** [multiverseweb/Dataverse#254]
The current script.js file could benefit from optimization and refactoring to improve performance and maintainability. This issue proposes several enhancements based on observed redundancies and performance bottlenecks.
Proposed Changes

_**Kindly add gssoc-ext with level and hacktoberfest-accepted lanels!**_ @multiverseweb 

**1. Debounce Scroll Events:**

- `Debounce` the scroll events (`changeCss`, progress) to minimize excessive function calls and improve performance during heavy scrolling. 
- Suggested debounce delay: 50ms.

**2. Consolidate Duplicate `validateForm` Functions:**

- Combine the two `validateForm` functions into one to prevent overwriting and ensure the function is consistent throughout the code.

**3. Refactor Theme Functions:**

- Reduce duplication between `light()` and `dark()` functions by consolidating them into a single `applyTheme()` function.
- This function would take a theme argument (`'light'` or `'dark'`) and apply respective styles.

**4. Simplify Error Handling in fetch Request for City Coordinates:**

- Refactor the `fetch` call in `addMarker` to use `.catch()` for error handling rather than try-catch for clarity and to follow a promise-based structure.

**5. Clean Up `updateIndicator` Function:**

- Remove any commented-out or unused code from `updateIndicator` to improve readability and reduce clutter.

**Comment by multiverseweb** [comment]
Sure @smog-root go ahead. Make sure the `functionality of the code remains undisturbed`. Also, `test all the pages` are working fine with the updated code in both themes before sending the PR. Good Luck!

**Comment by Tanisha0708** [comment]
i would like to work on this please assign me this issue 
@multiverseweb @smog-root
