### ISSUE TITLE
Add a popup for subscribing to newsletter

### ISSUE THREAD

**Issue by sezallagwal** [multiverseweb/Dataverse#256]
I want to add a popup for subscirbing to the newsletter please assign this to me under `gssoc-ext` and `hacktoberfest` @multiverseweb

**Comment by multiverseweb** [comment]
@sezallagwal have you started working on the issue? As we don't have a newsletter.

**Comment by sezallagwal** [comment]
@multiverseweb no not yet and if you don't have I will add it

**Comment by multiverseweb** [comment]
No actually I've different plans for providing updates about the software to the users. We don't need news letter, so I'm closing the issue. 
Sorry if you had any inconvenience.
Good Luck!
