### ISSUE TITLE
Glass Morphism inspire login and signup page

### ISSUE THREAD

**Issue by amiya-cyber** [multiverseweb/Dataverse#263]
Redesign your entire login and signup page according to the glass morphism design
![Create-A-Glassmorphism-Login-Form-in-HTML-and-CSS-only](https://github.com/user-attachments/assets/0f70f267-16ae-45ff-90f6-ec8151b629a6)

please assign add level 3 label @multiverseweb

**Comment by multiverseweb** [comment]
The login and signup page has already been redesigned under #237, therefore I'm closing this issue.
