### ISSUE TITLE
Want to improve  login.html and signup.html

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [multiverseweb/Dataverse#266]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

 Email Validation
Current: You have basic regex validation for the email.
Password Validation
Current: Password requirements are mentioned but not enforced in the validation.
User Feedback
Current: Alerts are used for feedback.
Clear Input Fields on Successful Login
Current: The input fields are cleared after checking validity.
Security Features
Current: Basic validation is present
### Proposed Solution

Email Validation 
Improvement: Consider adding more specific error messages for invalid email formats.
Password Validation
Improvement: Implement actual checks to enforce these rules before allowing the login
User Feedback
Improvement: Consider displaying error messages directly in the UI instead of using alert boxes, as it enhances user experience.
Clear Input Fields on Successful Login
Improvement: Only clear fields if the login is successful, not before. Move the clearing code to after the redirection.
Security Features
Improvement: Consider implementing additional security features, such as rate limiting on login attempts and two-factor authentication for enhanced security.

**Comment by multiverseweb** [comment]
Sure @JahnavikaGopalbvrith, go ahead. Make sure to use the same UI of the alert box as the one that appears when you click on `Get Dataverse`:
![image](https://github.com/user-attachments/assets/099c46e5-3b2e-44bd-b783-c1f23b30c01a)

**Comment by JahnavikaGopalbvrith** [comment]
@multiverseweb Thank you for assigning. I will let you know the status soon.

**Comment by vibhamishra09** [comment]
i want to work at this issue

**Comment by multiverseweb** [comment]
@vibhamishra09 The issue has been assigned already, I'll assign it to you in 2-3 days if the current assignee is inactive.

**Comment by JahnavikaGopalbvrith** [comment]
@multiverseweb I am working on this. I will PR you soon. Please do not assign it to anybody.
