### ISSUE TITLE
I wanna Add Scroll Animations 

### ISSUE THREAD

**Issue by Mallik-vinukonda** [multiverseweb/Dataverse#267]
I want to add Scroll Animations with Framer motion , to enhance the User experience and make the website looks stunning

**Comment by Mallik-vinukonda** [comment]
Hi @multiverseweb  
Your Current Website looks , so good but I wanna add those scroll animations much much more smoothly, and I can apply this animations to contributers page too , I will send you the video by tmrw Afternoon

**Comment by multiverseweb** [comment]
Okay so you're talking about the fade-in animation at the bottom of the screen right?

**Comment by multiverseweb** [comment]
> Okay so you're talking about the fade-in animation at the bottom of the screen right?

Hey @Mallik-vinukonda, are you still interested in working on this issue?

**Comment by Sankalp13353** [comment]
I would be grateful if you could assign this issue to me. I am eager to contribute to this project and look forward to working on it. Please let me know if you need any additional information from my side.
