### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by Kavish-Paraswar** [multiverseweb/Dataverse#270]
![image](https://github.com/user-attachments/assets/1e0324c5-6a06-4365-8404-977933706d48)
Adding social media icons to the footer making  UI better.
Please add GSOC 24 and hactoberfest tag along with level 1 to the issue.

**Comment by multiverseweb** [comment]
@Kavish-Paraswar 
Add GitHub, Discord and Gmail here:
![Screenshot 2024-11-06 061617](https://github.com/user-attachments/assets/2436b181-8b31-4085-8e59-649a3dbdbd2a)

Leave the links empty, I'll add them later 👍

**Comment by multiverseweb** [comment]
@Kavish-Paraswar reminder to make the stated changes, its the last chance to make your contribution count for `GSSoC`!
Good luck.
