### ISSUE TITLE
REDESIGN the entire CODE OF CONDUCT page

### ISSUE THREAD

**Issue by amiya-cyber** [multiverseweb/Dataverse#274]
i can redesign the entire code of conduct page

**Comment by jency1** [comment]
@amiya-cyber What type of page do you want to make ? Attach some relevant screenshots for better understanding.

**Comment by amiya-cyber** [comment]
![2024-11-03 (1)](https://github.com/user-attachments/assets/4d41b848-9581-49fd-b02a-9605acf4bf27)

i can design this by adding some hover effects and also some designing

**Comment by jency1** [comment]
@amiya-cyber What type of hover effects will you add? Show some example. Make sure it should be related to the website's asthetics.
