### ISSUE TITLE
REDESIGN the entire LICENSE page

### ISSUE THREAD

**Issue by amiya-cyber** [multiverseweb/Dataverse#275]
REDESIGN the entire LICENSE page

**Comment by jency1** [comment]
@amiya-cyber What type of page do you want to make? Attach some relevant screenshots for better understanding.

**Comment by amiya-cyber** [comment]
![2024-11-03 (2)](https://github.com/user-attachments/assets/24e5ed22-85e5-4e67-91cf-a43e7fddea21)
i can resdesign this with some effects

**Comment by jency1** [comment]
@amiya-cyber What type of hover effects will you add? Show some example. Make sure it should be related to the website's asthetics.
