### ISSUE TITLE
Automation of project structure updation using GitHub workflows and Python scripts

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [multiverseweb/Dataverse#277]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The Project Structure is not available to the Contributors, which might cause difficulties for the Contributors to figure out issues. It would also create difficult for the Contributors to contribute to the repository as it grows in size.

### Proposed Solution
To make it easier for the Contributors to refer to a structure, making the navigation of the repository much easier. I also want to automate the updation of the Project Repository to reduce workload, so that you can focus on the issues and PRs.

### Screenshot/Mockup (Optional)

Sample of how the workflow would be automated and the project structure after updation in readme:
![image](https://github.com/user-attachments/assets/81e8ca29-70d3-421e-aabc-1a2e428f13d5)

![image](https://github.com/user-attachments/assets/0bc44243-5a2a-4e6e-8afc-e0dd9097515f)

### Alternatives Considered

None.

### Additional Context

None.

### Requirement/Document

None.

I am willing to work on this issue.

**Comment by multiverseweb** [comment]
@rajdeepchakraborty-rc make sure you add the repo structure in `Documentation` directory.

**Comment by rajdeepchakraborty-rc** [comment]
@multiverseweb Placing the **README.md** file within the `.github` folder may not be ideal. I believe positioning it at the root level, outside of any directory, would enhance visibility and accessibility. Please share your thoughts on this approach.

**Comment by multiverseweb** [comment]
@rajdeepchakraborty-rc sure, you can move it to the root directory.

**Comment by multiverseweb** [comment]
Also, @rajdeepchakraborty-rc, can you check if the workflow is working fine [in CodeIt](https://github.com/multiverseweb/CodeIt)? I think the `PROJECT_STRUCTURE.md` file is not updating dynamically.

**Comment by rajdeepchakraborty-rc** [comment]
> Also, @rajdeepchakraborty-rc, can you check if the workflow is working fine [in CodeIt](https://github.com/multiverseweb/CodeIt)? I think the `PROJECT_STRUCTURE.md` file is not updating dynamically.

Sure I will give it a check.

**Comment by rajdeepchakraborty-rc** [comment]
> Also, @rajdeepchakraborty-rc, can you check if the workflow is working fine [in CodeIt](https://github.com/multiverseweb/CodeIt)? I think the `PROJECT_STRUCTURE.md` file is not updating dynamically.

@multiverseweb I have resolved the issue and opened a PR. Please review it at your convenience.
