### ISSUE TITLE
The navbar

### ISSUE THREAD

**Issue by sachinggsingh** [multiverseweb/Dataverse#279]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

The navbar is not completely visible the right most part of it is being sliced 

### Expected Behavior
It should be visible completely

### Screenshot

![Screenshot 2024-11-04 184207](https://github.com/user-attachments/assets/cffdfe9f-5448-4bad-85e8-c018747004bd)

### Proposed Solution
Need to fix the padding in between the navbar

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by multiverseweb** [comment]
@sachinggsingh it cannot be fixed by reducing the padding between navbar tabs as it depends on the width of the screen. The navbar is scrollable and all the tabs can be seen by scrolling
