### ISSUE TITLE
Enable Progressive Web App (PWA) for the site

### ISSUE THREAD

**Issue by amiya-cyber** [multiverseweb/Dataverse#281]
A PWA or Progressive Web Application allows users to install the site as a desktop or android application. It will enhance user experience and drive organic traffic. It also allows users to access the site offline by pre-downloading assets such as files or images as cache memory.

**TURN YOUR WEBSITE INTO A WEB APP**

Why Enable PWA?
Enabling Progressive Web Apps (PWAs) enhances a website by providing a native app-like experience with several key benefits:

1. Offline Access: Users can access content without an internet connection.
2. Fast Loading: PWAs load quickly, improving performance even on slow networks.
3. Home Screen Installation: Users can install PWAs on their devices without app store hassles.
4. Push Notifications: Engage users with timely notifications, even when the app isn’t open.
5. Responsive Design: PWAs work seamlessly across different devices and screen sizes.

![1_R2PVSj_iWUQr4GYbcu2j1A](https://github.com/user-attachments/assets/e89cc95e-a141-4256-ae74-5e4912b88882)

ASSIGN WITH LEVEL 3

**Comment by multiverseweb** [comment]
@amiya-cyber just explain to me in brief about how you are going to do this . Also, will the users be notified about feature or some sort of `install button` will appear on the website or what?

**Comment by amiya-cyber** [comment]
Do you want any video proof

**Comment by amiya-cyber** [comment]
I will create a manifest json dila and service worker.js file and then I will register the service worker and then I will link them all with index.html by which the whole website can be used as a application there will be a install function Also by which it will get installed on your desktop and the content can be seen while being offline

**Comment by amiya-cyber** [comment]
Assign me with level 3 I will not disappoint you with the results

**Comment by multiverseweb** [comment]
@amiya-cyber okay so ahead. Make sure this feature does not disturb the functionality of existing website. Also, test the introduced feature in both desktop and mobile phone before sending the PR.

**Comment by amiya-cyber** [comment]
> @amiya-cyber okay so ahead. Make sure this feature does not disturb the functionality of existing website. Also, test the introduced feature in both desktop and mobile phone before sending the PR.

Yeah sure I will upload the proof of the video
