### ISSUE TITLE
Adding a new feedback and rating page

### ISSUE THREAD

**Issue by shriyadindi** [multiverseweb/Dataverse#283]
Adding a new feedback and rating page.

**Comment by multiverseweb** [comment]
Hello @shriyadindi, the feedback form already exists at the bottom of the page, can you add the ` ⭐ Rating feature` to it? The ratings should be saved in user feedback too.

**Comment by shriyadindi** [comment]
@multiverseweb Okay, I'll add the rating feature to the feedback form and can I enhance the styling and modify the form a bit as it looks too small on the page and increase the text area?

**Comment by jency1** [comment]
@shriyadindi Just add the rating feature as of now.
