### ISSUE TITLE
[Feature Request]: Show 404 Error Page for Invalid URLs

### ISSUE THREAD

**Issue by RachitSahu26** [multiverseweb/Dataverse#287]
This issue will handle situations where users enter an invalid URL and display a custom 404 error page instead of redirecting them to the homepage.

**Comment by multiverseweb** [comment]
@RachitSahu26 the custom 404 error page already exists [here](https://github.com/multiverseweb/Dataverse/blob/main/.github/404.html). But it is not opening when someone clicks an invalid URL. Maybe there is some issue in file positioning (path). Can you fix it please? I'm assigning `level1` for the same. Don't forget to update the file paths used for css accordingly.
