### ISSUE TITLE
Beautify the navbar section

### ISSUE THREAD

**Issue by Jay-1409** [multiverseweb/Dataverse#29]
Hi @multiverseweb, 
I found that the hamburger menu/ side menu in the navbar could be beautified 
here is what i did 

<img width="959" alt="image" src="https://github.com/user-attachments/assets/a509a115-a41c-4d7e-ac7d-074b6e85d78d">

please assign this to me under hacktoberfest2024 and gssoc2024 extd
thank you

**Comment by multiverseweb** [comment]
Hey @Jay-1409, I believe the existing design matches with the overall aesthetic of the software. I appreciate the idea. Thanks.
