### ISSUE TITLE
Link to documentation in the main page returning a 404 due to the current folder structure or due to falsely path.

### ISSUE THREAD

**Issue by Mannega** [multiverseweb/Dataverse#290]
![dataverseReadme404](https://github.com/user-attachments/assets/1611b7e6-e982-47ff-afb5-1c84623fc823)
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

When clicking on the 'Documentation' link in the footer of the main page (https://multiverse-dataverse.netlify.app/), it returns a 404.

### Expected Behaviour

It should correctly link to the README.md file in the GitHub repository.

### Screenshot

Screenshot attached below.

### Proposed Solution

Change the README.md file from the .github file to the root directory.
![dataverseReadme404](https://github.com/user-attachments/assets/d4c7bfcf-f307-4166-9350-7ca282456a99)

**Comment by multiverseweb** [comment]
@Mannega assigned.
