### ISSUE TITLE
[Repo] Create Auto Label Workflow for Pull Requests

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#299]
### Current Behaviour

There is no auto label workflow for pull requests.

### Expected Behaviour

Newly opened PRs should be automatically labeled with `Review Queued` label of `#faff00` color.

**Comment by sucharitaaa3100** [comment]
please assign this issue to me

**Comment by multiverseweb** [comment]
Sure @sucharitaaa3100, go ahead!

**Comment by multiverseweb** [comment]
@sucharitaaa3100  reminder to make a PR soon, its the last chance to make your contribution count for `GSSoC`!
Good luck.
