### ISSUE TITLE
Support plotting RadarChart in software.

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#3]
The software currently displays only the button for RadarChart, the code is yet to be written and linked.
> [!IMPORTANT]
> Keep the GUI same as other plots and use the predefined color map.

**Comment by Rohan20-10** [comment]
Hi @multiverseweb  Myself Rohan Parab , I would be more than happy to contribute towards this project of Dataverse.
Will u pls assign this issue to me

**Comment by multiverseweb** [comment]
Sure, @Rohan20-10 . Good luck!

**Comment by Rohan20-10** [comment]
Hi @multiverseweb just wanted a clarification from you regarding the x_var input, whether it should be kept as a string or int because the radar charts are usually like this [image](https://www.excelmojo.com/wp-content/uploads/2023/02/Radar-Chart-in-Excel.png) its like string custom inputs with no class widths so should I take input to add how many values of x independent variable?

**Comment by multiverseweb** [comment]
Hey @Rohan20-10, Yes I think we should take the number of variables as input. I've set the number of independent variables count to `16` in other plots. So, I think we should keep it `16` in this too. Take the variable names as `string` and use them in the chart. Let me know if you need further clarification.

**Comment by Rohan20-10** [comment]
@multiverseweb thanks for resolving my query. So the count of independent and dependent both would be 16 right?

**Comment by multiverseweb** [comment]
@Rohan20-10 Yes.

**Comment by Rohan20-10** [comment]
@multiverseweb Is this output fine?
![Figure_1](https://github.com/user-attachments/assets/d3984d25-0818-4938-a3fc-e098eb9c3969)
Fixing some small bugs & issues
Is there any specific format for pull request ?

**Comment by multiverseweb** [comment]
Looks good. Just create a new branch `gssoc-yourName` before sending the pull request. That will help me merge easily. Also, have you linked the user input with GUI? just like other graphs in the software.

**Comment by Rohan20-10** [comment]
Yes @multiverseweb I have done that just forgot to attach the screenshot
