### ISSUE TITLE
[Website] Fix the theme button

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#302]
The `indicator` div in theme button area is not positioned correctly.
![image](https://github.com/user-attachments/assets/74beba5f-9672-4458-bec0-56ebe68be2a5)

![Screenshot 2024-11-06 071300](https://github.com/user-attachments/assets/f811bfbe-733c-4dcd-bc0c-4af8cf212e1d)

Fix its position without changing the functionality. (color changing on dark mode).

**Comment by amin-xiv** [comment]
Can I get assigned?

**Comment by multiverseweb** [comment]
Sure @amin-xiv
