### ISSUE TITLE
[Website] Contributions count not updating

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#303]
### Issue

The count of contributions in `Contributors Page` is not updating.

### Screenshot
![Screenshot 2024-11-06 072416](https://github.com/user-attachments/assets/0a96c1d3-5d38-4a44-b40a-26e44374cf2c)

**Comment by Rohan20-10** [comment]
@multiverseweb Please assign this issue to me. I will work on it.

**Comment by multiverseweb** [comment]
@Rohan20-10 sure, go ahead.

**Comment by multiverseweb** [comment]
@Rohan20-10 this issue has been resolved, so I'm closing it. Let me know if you want to discuss this further.
