### ISSUE TITLE
[Software] Display version in software

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#305]
Display the version of software at bottom left corner of the `software's Home Page`.
The current version is **6550(24) `Latest`**

![Screenshot (128)](https://github.com/user-attachments/assets/15af9352-18a7-4bbc-958a-db01f1e451a3)

**Comment by Rohan20-10** [comment]
@multiverseweb Please assign this issue to me. I will work on it. Thanks.

**Comment by multiverseweb** [comment]
Okay @Rohan20-10, assigned.
