### ISSUE TITLE
[Website] Show a popup when the rating is sent to indicate sucess/failure.

### ISSUE THREAD

**Issue by amin-xiv** [multiverseweb/Dataverse#318]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

It current lacks the popup, which can be counter-intuitive, since a user might wonder whether it has been sent successfully or no, in which I am looking forward to get assigned to.

### Proposed Solution

Add a custom popup, or use the existing one(but edited) to suit this feature.

### Alternatives Considered

An ``alert();`` can simply be used, but why not make it better?

**Comment by multiverseweb** [comment]
Sure @amin-xiv, go ahead👍

**Comment by amin-xiv** [comment]
@multiverseweb Thanks
