### ISSUE TITLE
Cities not visible on contributions map.

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#32]
![image](https://github.com/user-attachments/assets/c665c721-0086-49f0-bb8a-593e7c9b8404)

**Comment by rishikaa1** [comment]
@multiverseweb i would like to work on this issue.

**Comment by multiverseweb** [comment]
@rishikaa1 Sure, assigned. Don't forget to create a new branch `gssoc-yourName` before sending the PR.

**Comment by rishikaa1** [comment]
@multiverseweb thanks!
