### ISSUE TITLE
Contributors , Total Contributions value showing wrong

### ISSUE THREAD

**Issue by souvikpramanikgit** [multiverseweb/Dataverse#324]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

I think the fetchData function uses a single fetch call to get all contributors, without handling pagination. GitHub’s API typically returns only up to 30 contributors per request (depending on the per_page value), and the code doesn't handle pagination. So, if there are more than 30 contributors, only the first 30 are returned, resulting in an incorrect contributor count.

### Expected Behaviour

I expect that it will show the actual Contributors , Total Contributions value

### Screenshot

![image](https://github.com/user-attachments/assets/d52953d4-c7bf-4af5-b25a-aeb44c2f9bc7)
![image](https://github.com/user-attachments/assets/0bda2689-7ce6-4d5f-81f7-2ad176458358)

**Comment by amin-xiv** [comment]
I got this 👌

**Comment by souvikpramanikgit** [comment]
but, i want to do.

**Comment by amin-xiv** [comment]
@souvikpramanikgit ok then my bad I didn't think you were doing it

**Comment by multiverseweb** [comment]
Go ahead @souvikpramanikgit
