### ISSUE TITLE
Documentation link in the side bar not working

### ISSUE THREAD

**Issue by amin-xiv** [multiverseweb/Dataverse#330]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

The documentation link is returning a 404 page.

### Expected Behaviour

Direct me instantly to the README file in the repository.

### Screenshot

![bug](https://github.com/user-attachments/assets/65ec3254-5a97-4396-a812-baa7a5bd3e7c)

### Proposed Solution

Correct the path to the README file.

**Comment by multiverseweb** [comment]
@amin-xiv assigned
