### ISSUE TITLE
[Website] User can login even though no password is provided.

### ISSUE THREAD

**Issue by amin-xiv** [multiverseweb/Dataverse#333]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

In the login page, a user can login without providing a password.

### Expected Behaviour

Alert or throw any error indicating that a password must be provided.

### Proposed Solution

Add error checking to prevent this issue.

### Technical Details

https://github.com/user-attachments/assets/a21551ad-2a20-492b-8af7-471a60d7a123

**Comment by multiverseweb** [comment]
Okay @amin-xiv, assigned!
