### ISSUE TITLE
[Website] Add 'Report a bug' form

### ISSUE THREAD

**Issue by amin-xiv** [multiverseweb/Dataverse#350]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

Currently, the users can't report any bugs directly through the website.

### Proposed Solution

Add a simple form in which the users, can report a bug, describe it, and may attach any screenshots/videos and then once it is submitted, it can be sent directly to a support email, so I'm thinking about using `multiverse.letter@gmail.com` as a support email. Let me know what you think.

### Screenshot/Mockup (Optional)

N/A

### Alternatives Considered

Maybe providing a link directly to the issues section in this repository.

### Additional Context

N/A

### Requirement/Document

N/A

**Comment by Rucha-Ambaliya** [comment]
I would like to work on this issue.
