### ISSUE TITLE
Enhance User Authentication and Data Security

### ISSUE THREAD

**Issue by Nayanpatel48** [multiverseweb/Dataverse#37]
Hi @multiverseweb ,

I'm interested in contributing to this project by **improving/adding user authentication and data security.**

I propose implementing:

```
Sign up a user (Email/Password)
Sign in a user
Sign out a user
Form Validation and Handle Errors
Handle User Authentication State
Email Verification
Forgot/Reset Password
Google Sign in
Facebook Sign in
Add, Get & Update Logged In User Data
Upload, Get & Update Logged In User Profile Picture.
```

I'm ready to discuss this further and contribute a pull request.

**Comment by multiverseweb** [comment]
@Nayanpatel48 yes, that can be useful for **notifying people with software updates**. Make sure you keep the design of sign in/log in page `according to the overall aesthetic` of the website and software. Do let me know if you want to discuss anything. Good luck!

**Comment by Nayanpatel48** [comment]
-My linked in :https://www.linkedin.com/in/patel-nayan-047317248?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app
-Keep in touch 😙
