### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [multiverseweb/Dataverse#39]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible .

Hey @multiverseweb I can work on this.

**Comment by multiverseweb** [comment]
@harish08102004 Now that is something interesting. Assigned.

**Comment by Shalinis19137** [comment]
I Would like to work with you , Can you please assign me this issue under gssoc-ext 2024

**Comment by harish08102004** [comment]
Hey @Shalinis19137 it's already closed

**Comment by Shalinis19137** [comment]
Ok sir,no problem 😊
