### ISSUE TITLE
Support plotting Heatmap in software.

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#4]
The software currently displays only the button for HeatMap, the code is yet to be written and linked.
> [!IMPORTANT]
> Keep the GUI same as other plots and use the predefined color map.

**Comment by chaheti89** [comment]
Can this issue please be assigned to me?

**Comment by multiverseweb** [comment]
@chaheti89 okay, assigned.

**Comment by Anushka184** [comment]
Can you pls assign this issue to me @multiverseweb

**Comment by multiverseweb** [comment]
@Anushka184 I have assigned this issue already. I'm assigning it to you too but that reduces the chances of merging. However, you can check out [this issue](https://github.com/multiverseweb/Dataverse/issues/7). Both of these are very similar.

**Comment by multiverseweb** [comment]
Any updates @chaheti89? Do let me know if you need any help.

**Comment by multiverseweb** [comment]
@chaheti89 sure, no hurries.

**Comment by Rohan20-10** [comment]
@multiverseweb can I work on this issue, as it is very similar to the ones I did previously?

**Comment by multiverseweb** [comment]
Sure, @Rohan20-10. Assigned.

**Comment by Rohan20-10** [comment]
@multiverseweb how many rows and columns are required? As usual, should it be 16 each?
Since the total number of values will be rows*cloumns.

**Comment by multiverseweb** [comment]
@Rohan20-10 Yes 16. Do you know why I set the upper limit to 16?
It's just because in the list `color`, I have added only 16 colors. We can increase that anytime. 
There is an effective thing we can do, we can set a variable `maxLimit` and set it to 16. We can use that variable everywhere in the program instead of the number `16`.

What do you think?

If you're interested in this you can either raise a new issue or solve this in the same PR.

**Comment by Rohan20-10** [comment]
> @Rohan20-10 Yes 16. Do you know why I set the upper limit to 16? It's just because in the list `colors`, I have added only 16 colors. We can increase that anytime. There is an effective thing we can do, we can set a variable `maxLimit` and set it to 16. We can use that variable everywhere in the program instead of the number `16`. The variable must be defined near the list `colors`. What do you think?
> 
> If you're interested in this you can either raise a new issue or solve this in the same PR.

Yeah sure I would like to do that. Surely I will raise a issue for this. Thanks for your input due to that I got to know the reason behind this number 16.

**Comment by Rohan20-10** [comment]
@multiverseweb Issue is on the verge of completion by tomorrow it will be fixed. Thanks.
