### ISSUE TITLE
Enhance Data Visualization with Plotly Integration

### ISSUE THREAD

**Issue by Sneha22072005** [multiverseweb/Dataverse#40]
I propose enhancing the data visualization features in the Dataverse project by integrating Plotly. Currently, we are using Matplotlib for visualizations, which limits interactivity and user engagement. The goal is to replace existing Matplotlib visualizations in dataVisualization.py with Plotly's interactive charts, providing a more dynamic and user-friendly experience for exploring data. This enhancement will improve usability by allowing users to interact with graphs through zooming, panning, and tooltips.

want to work on this

**Comment by multiverseweb** [comment]
Hey @Sneha22072005, actually the file dataVisualization.py is useless. It wasn't imported in the mainGUI.py. I have deleted it in the latest commit. However, integrating the project with plotly is a nice option. I believe replacing entire matplotlib code with plotly can be a difficult task. How about integrating plotly in the newer features like `plot equations`.

![image](https://github.com/user-attachments/assets/513834b6-3ed4-40ea-a637-0aa8631df918)

That's just my opinion. What do you think?

**Comment by Sneha22072005** [comment]
Basically that should mean I'll be working with the plot_line function perhaps?

**Comment by multiverseweb** [comment]
@Sneha22072005 the current plot_line function in mainGUI.py is triggered when someone clicks on this `plot` button:

![image](https://github.com/user-attachments/assets/ab57e2e2-4e4b-40f4-a612-dce5876bd182)

this button works for all types of charts.

I was suggesting you to work on `Plot equations` feature that will support plotting equations on the graph such as y=x**2 or y=3x + 5, etc.

You can find the button under `data visualization` section (on the left sidebar).

Also, if you think this is not your expertise, you can work on `Heatmap`, that is the only feature left for development.

**Comment by Rizvi-Faiz** [comment]
can you assign this issue to me

**Comment by Sneha22072005** [comment]
> @Sneha22072005 the current plot_line function in mainGUI.py is triggered when someone clicks on this `plot` button:
> 
> ![image](https://private-user-images.githubusercontent.com/131871888/373694402-ab57e2e2-4e4b-40f4-a612-dce5876bd182.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTg2MTUsIm5iZiI6MTcyODA1ODMxNSwicGF0aCI6Ii8xMzE4NzE4ODgvMzczNjk0NDAyLWFiNTdlMmUyLTRlNGItNDBmNC1hNjEyLWRjZTU4NzZiZDE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjExNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjY2YWZkOWNkZWMyNGE0OWRmNTFiMWE3MDM3NmZmZmFhZTZlODA2ZmJlMGYwZDI2M2RjYjdhZTFjNDQ1NzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jBwQVlWAYpqKTXrC7vWhuUJ3q5tl-iCU_qm3fHv4buY)
> 
> this button works for all types of charts.
> 
> I was suggesting you to work on `Plot equations` feature that will support plotting equations on the graph such as y=x**2 or y=3x + 5, etc.
> 
> You can find the button under `data visualization` section (on the left sidebar).
> 
> Also, if you think this is not your expertise, you can work on `Heatmap`, that is the only feature left for development.

im already working on it

**Comment by multiverseweb** [comment]
@Sneha22072005 okay, good luck.
