### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#45]
Make the steps of setting-up **`Dataverse`** on the computer easily understandable and simplified in README.md .

**Comment by AryaEjoumalai** [comment]
Hi, can you assign me to this issue

**Comment by Rizvi-Faiz** [comment]
Can you assign this issue to me

**Comment by multiverseweb** [comment]
@AryaEjoumalai Sure. Make sure the set-up instructions are clear and include all the requisites.

**Comment by jyothimanoj12** [comment]
can you assign this issue to me

**Comment by multiverseweb** [comment]
Sorry @jyothimanoj12 @Rizvi-Faiz, the issue has been assigned already.

@AryaEjoumalai any updates? Let me know if you need any kind of help.

**Comment by AryaEjoumalai** [comment]
Yep, I'm working on visuals and few other stuff, will update you soon
