### ISSUE TITLE
Adding Footer icons and Description 

### ISSUE THREAD

**Issue by RiddhiM170904** [multiverseweb/Dataverse#47]
Footer can be made more attractive by adding social media icons with redirecting links and description and contact details for the site.
![image](https://github.com/user-attachments/assets/f3586095-09cc-44bb-a418-c180a596a379)

Please assign me gssoc'24 extd and hacktoberfest badge for this issue.

**Comment by ayushiu** [comment]
please assign this issue to me under gssoc-extended

**Comment by multiverseweb** [comment]
@RiddhiM170904 sure. Add Dataverse's logo with the name `Dataverse` along with social media icons for GitHub, Discord and Gamil. I'lladd the links later 👍

**Comment by LitZeus** [comment]
hey @multiverseweb can I look into the issue? I will be looking it into right away!

**Comment by RiddhiM170904** [comment]
completed #68
