### ISSUE TITLE
Fix contact page

### ISSUE THREAD

**Issue by devarsheecodess** [multiverseweb/Dataverse#49]
The input text on contact page is not visible. I want to fix this issue along with other minor issues like appropriate aligning, spacing, etc. plz assign me this issue with gssoc-extd and appropriate level labels. I want to work on this issue
![Screenshot 2024-10-04 173956](https://github.com/user-attachments/assets/11f2fa5c-ab22-4ef6-b976-e8110e69ffbe)

**Comment by multiverseweb** [comment]
@devarsheecodess Sure, good luck!
