### ISSUE TITLE
Create PDF report for tracking finance.

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#5]
Currently, the software only asks the user if they want to download today's finance report. Add the code for pdf generation with the name `username-currentDate-Dataverse.pdf`.

- The report must contain the date, username, image of the line chart, pie chart, bar graph and the name `Dataverse` with logo.

![image](https://github.com/user-attachments/assets/96925f4d-d1bc-4cfb-87cb-2f0343218d4b)

**Comment by ruchikakengal** [comment]
I would like to work on this project

**Comment by multiverseweb** [comment]
@ruchikakengal sure, looking forward to your contributions. Can you solve this issue? If no, wait for the issues that match your skill, or simply open new issues.

**Comment by Rohan20-10** [comment]
Hi @multiverseweb Myself Rohan Parab , I would be more than happy to contribute towards this project of Dataverse.
Will u pls assign this issue to me so that I can work on this issue.

**Comment by ruchikakengal** [comment]
yes i solve this issue

**Comment by multiverseweb** [comment]
Sure, @ruchikakengal @Rohan20-10 , I've assigned the issue to you. Don't forget to keep the design of pdf report similar to that of the software.

**Comment by multiverseweb** [comment]
@ruchikakengal do let me know if you need any kind of help.

**Comment by multiverseweb** [comment]
@Rohan20-10 You're right. You can try running it. But I couldn't design the pdf nicely. I want the pdf to be visually appealing.
Would you like to work on this issue too?

**Comment by Rohan20-10** [comment]
Yes @multiverseweb you have previously assigned this issue to me

**Comment by multiverseweb** [comment]
@Rohan20-10 sure, no hurries.
