### ISSUE TITLE
Add images to buttons

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#51]
Add little images to the buttons. The images must represent the type if plot and should be white PNGs.

This is what the current buttons look like:
![image](https://github.com/user-attachments/assets/8aac972d-71b6-4783-b8b2-a510a01a6db8)

This is what we want:

![image](https://github.com/user-attachments/assets/22a9f757-2ff0-4cfe-8eb4-cdee45df4213)

>[!IMPORTANT]
>Store the images in `Dataverse/software/images` folder.

You can find the images on internet easily. Let me know if you need any image by commenting below.

**Comment by sumana-2705** [comment]
hello @multiverseweb can I take up this issue?

**Comment by Darshan3690** [comment]
hello @multiverseweb  i also interest for this issue . can please assign me ?

**Comment by jyothimanoj12** [comment]
hello @multiverseweb  i want to work on this issue can you assign it to me as i have done this before

**Comment by multiverseweb** [comment]
@sumana-2705 Sure, go ahead!

**Comment by Rohan20-10** [comment]
@multiverseweb I will be more than happy to work on this issue. Will you please assign this issue to me?

**Comment by Rohan20-10** [comment]
@jency1 I will be more than happy to work on this issue. Will you please assign this issue to me?

**Comment by multiverseweb** [comment]
@Darshan3690 @jyothimanoj12 @Rohan20-10 Due to the delay in PR from @sumana-2705, I'm assigning the issue to you. 
I will merge whoever comes first. 😅

**Comment by Darshan3690** [comment]
hi @multiverseweb  please assign me for this issues . I will come back with PR.
