### ISSUE TITLE
Code of Conduct and License Page on website

### ISSUE THREAD

**Issue by anshika-1102** [multiverseweb/Dataverse#52]
![image](https://github.com/user-attachments/assets/52e8ccad-a5c8-41d3-b26b-54328933564b)

I want to add content with proper styling to the code of conduct on the website too.

I also want to align the contents of License page in a proper way.

**Comment by multiverseweb** [comment]
Sure, go ahead!

**Comment by anshika-1102** [comment]
@multiverseweb The issue is not a documentation issue. It is an 'enhancement' label issue because I am working on the website navbar section pages and not the GitHub repo sections.

**Comment by multiverseweb** [comment]
Yeah sure @anshika-1102. In my opinion, the alignment looks good but the font size is a little too big.

**Comment by anshika-1102** [comment]
@multiverseweb thanks for the suggestion. I'll just make the changes.
