### ISSUE TITLE
Bug in GUI

### ISSUE THREAD

**Issue by multiverseweb** [multiverseweb/Dataverse#53]
### Bug:

- After plotting one graph successfully, if the user tries to plot any other chart again, the `Plot` button disappears.

> This is the error we get in terminal when the user clicks on any plot graph button `again`.
![image](https://github.com/user-attachments/assets/ca18cfc1-016e-4137-9c09-636d79600cee)

Here, the plot button is not displayed:
![Screenshot 2024-10-05 085822](https://github.com/user-attachments/assets/306b739e-2fb0-4fe6-84b8-532a60475e55)

### Expected Behaviour:

- The screen should be cleared (data entry labels) when the user clicks on any plot graph button `again`.
- The window label for new data input for the new graph should be displayed.

**Comment by Darshan3690** [comment]
Hi, @multiverseweb assign me ?

**Comment by Charul00** [comment]
can i do this 
please assign to me @multiverseweb

**Comment by Charul00** [comment]
please label level 3 its been quit hard i knot how to solve this @multiverseweb

**Comment by Darshan3690** [comment]
hi @multiverseweb  assign me.

**Comment by Darshan3690** [comment]
hi,assign me? @multiverseweb

**Comment by Rohan20-10** [comment]
@multiverseweb can I work on this issue?

**Comment by Rohan20-10** [comment]
@jency1  can I work on this issue as I have previous contribution experiences.

**Comment by multiverseweb** [comment]
Sure @Rohan20-10, go ahead.

**Comment by multiverseweb** [comment]
Any updates @Rohan20-10? This is a `high priority` issue as this is a major bug. It creates a lot of problems while testing PRs too.
Let me know if you need further clarification about what the issue exactly is.

**Comment by Rohan20-10** [comment]
@multiverseweb Firstly Sorry for the delay. Actually, I have got the issue still will you please send me the video showing the bug into the GUI as there are many errors associated with it. It would better clarify my doubts. Thnks.

**Comment by multiverseweb** [comment]
@Rohan20-10 Sure, here is the video:

https://github.com/user-attachments/assets/a6024df1-583e-4898-8e8a-58ca6ee3b908

As you can see, the software works fine for the first plot, but when we try to visualize data again (any form line, bar, histogram, etc), the `Plot` button does not show up. 

The error it triggers is:
![image](https://github.com/user-attachments/assets/7a156579-e01f-47ee-a375-d9b4afd771d4)

It occurs when we click on `Enter Values` button like 00:49 in the video.

Feel free to ask if you encounter any doubts.

**Comment by multiverseweb** [comment]
@Rohan20-10 don't forget to pull the latest commits from the repo as several changes have been made in the `main.py` file.

**Comment by Rohan20-10** [comment]
Thanks @multiverseweb I will fix this issue and get back to you.
