### ISSUE TITLE
Contact Us Form Email Validation Missing & Text Visibility Issue.

### ISSUE THREAD

**Issue by Shariq2003** [multiverseweb/Dataverse#54]
The Form validation for email is missing in contact us form and its text visibility is too low.

https://github.com/user-attachments/assets/a6e7edac-1905-40ec-9364-61ab51e9cdf7

@multiverseweb Plesase assign this to me.

**Comment by multiverseweb** [comment]
@Shariq2003 similar issue #11 already exists and has been assigned.
