### ISSUE TITLE
Back-To-Top Button Visibility Issue in Website

### ISSUE THREAD

**Issue by Shariq2003** [multiverseweb/Dataverse#55]
Back-To-Top Button in the website work improperly and degrade the UI and UX.

https://github.com/user-attachments/assets/51dd5b50-a3ad-43bb-a647-c0e8ca5f75a8

@multiverseweb please assign this to me.

**Comment by multiverseweb** [comment]
okay @Shariq2003, make sure the design must match with the overall aesthetic of website and software.

**Comment by Shariq2003** [comment]
> okay @Shariq2003, make sure the design must match with the overall aesthetic of website and software.

Sure

**Comment by Shariq2003** [comment]
@multiverseweb please check my PR
