### ISSUE TITLE
Adding scroll feature to logos in "Here are some examples of what you can do with Dataverse" section to increase functionality

### ISSUE THREAD

**Issue by LitZeus** [multiverseweb/Dataverse#56]
### Making the logos bar scroll automatically in the section - `Here are some examples of what you can do with Dataverse`

@multiverseweb can you assign it to me under `hacktoberfest-accepted` and `gssoc-ext` label?

**Comment by multiverseweb** [comment]
Okay @LitZeus, assigned. Make sure the scroll animation is infinite and in one direction. Also, don't forget to follow these [contribution guidelines](https://github.com/multiverseweb/Dataverse?tab=readme-ov-file#contributions) before sending the PR.

Good luck!
