### ISSUE TITLE
Feat: issue/pr template 

### ISSUE THREAD

**Issue by Abhi0049k** [multiverseweb/Dataverse#60]
@multiverseweb
We need to add standardized templates for issues and pull requests (PRs) to maintain consistency and improve the clarity of communication in our project. This will ensure that all contributors follow a structured approach when creating issues or submitting PRs.

**Comment by multiverseweb** [comment]
@Abhi0049k 
Good idea, will these headings be enough? 
- Current Behaviour
- Expected Behaviour
- Screenshot
- Proposed solution.

**Comment by GauriSachan** [comment]
> @Abhi0049k Good idea, will these headings be enough?
> 
> * Current Behaviour
> * Expected Behaviour
> * Screenshot
> * Proposed solution.

hey @multiverseweb can you please assign appropriate labels to my pr #9 ?

**Comment by Abhi0049k** [comment]
> @Abhi0049k Good idea, will these headings be enough?
> 
> * Current Behaviour
> * Expected Behaviour
> * Screenshot
> * Proposed solution.

I think this should be enough.

**Comment by Abhi0049k** [comment]
by the way can you assign this issue to me?

**Comment by Abhi0049k** [comment]
and one more thing can you add hacktoberfest and gssoc-ext labels
