### ISSUE TITLE
Add links to Social Media Handle

### ISSUE THREAD

**Issue by VivekShahare04** [multiverseweb/Dataverse#64]
**Enhanced Visibility**: Increases online presence and audience reach.
**Improved Engagement**: Facilitates interaction through likes, shares, and comments.
**Brand Recognition**: Strengthens consistent branding across platforms.
**Increased Traffic**: Drives more visitors to social media accounts.
**Real-time Updates**: Provides users with timely news and promotions.
**SEO Benefits**: Contributes positively to search engine rankings.
**Builds Trust**: Establishes credibility and social proof.
**Cross-Promotion**: Allows sharing of content between social media and the website.

@Tejas-Gupta-7

**Comment by VivekShahare04** [comment]
provide me mail,discord id i will do it
@Tejas-Gupta-7 
please tag me with gssoc and hacktoberfest

**Comment by multiverseweb** [comment]
@VivekShahare04 similar issue #47 already exists and has been assigned.

**Comment by VivekShahare04** [comment]
@Tejas-Gupta-7 ok so is it resolve? if not than assign me i will solve it now and make a pull request.

**Comment by multiverseweb** [comment]
@VivekShahare04 comment the same on that issue.
