### ISSUE TITLE
Fixing the send button issue in the form

### ISSUE THREAD

**Issue by tarunkumar2005** [multiverseweb/Dataverse#67]
![image](https://github.com/user-attachments/assets/44733caa-2ec4-4b1c-88a8-daa2018cfce6)

Fixing the send button issue in the form to make it better for ui/ux. 

Assign this to me under gssoc 2024 ext and hacktoberfest. i will work on fixing it.

**Comment by shubhrangipathak** [comment]
hey @tarunkumar2005 , Assigned and make sure it aligns with the other fields. you can start working on it.

**Comment by tarunkumar2005** [comment]
@shubhrangipathak Add the level to it too

**Comment by tarunkumar2005** [comment]
@shubhrangipathak I have created the pull request you can check, and merge it and assign that to me and put relevent labels on it like gssoc 2024 ext, hacktoberfest and level too you haven't added it in the issue.

**Comment by tarunkumar2005** [comment]
@shubhrangipathak Its still not check and merged its been long till it is active can you check the PR.
