### ISSUE TITLE
Fix the LOGO

### ISSUE THREAD

**Issue by adityakr0660** [multiverseweb/Dataverse#70]
The logo is not aligned with the website's design, but I can improve it to make it more attractive and visually appealing to users.
![ddd](https://github.com/user-attachments/assets/3e6456aa-538c-457f-ae03-fdf45a29a84a)

Please @multiverseweb  

assign this task to me, as I am confident I can improve the logo by giving it a modern and attractive look

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..

**Comment by multiverseweb** [comment]
@adityakr0660 can you share some logo ideas before working on the same?
