### ISSUE TITLE
Improving Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [multiverseweb/Dataverse#78]
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

The current Loading has no preloader. The screen becomes blank when the website loads. 

### Proposed Solution

Enhancing the preloader, and improving the styling of the preloader design would greatly improve the user experience and website presentation

### Screenshot/Mockup (Optional)

https://github.com/user-attachments/assets/02b8e200-1b4c-4bb2-a15d-4973003fcd51

### Tasks:

- Redesign the preloader for better visual appeal.
- Improving the preloader.
@shubhrangipathak  can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by shubhrangipathak** [comment]
@VidhanThakur09 , Assigned

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me
