### ISSUE TITLE
 Add Header Section to Web Page for Improved Navigation

### ISSUE THREAD

**Issue by tejasam571** [multiverseweb/Dataverse#79]
**Current Behaviour**
The web page currently lacks a dedicated header section, which impacts both the visual appeal and the functionality. Without a header, users find it challenging to navigate through different sections of the website, leading to a less intuitive user experience. Adding a header can greatly improve navigation and make the interface more cohesive and user-friendly.

**Proposed Solution**
A header section should be added at the top of the page. This header would include the following elements:

Website logo (for brand identity)
Navigation links (Home, Quiz, About, Contact)
Optionally, a search bar or a user profile dropdown for quick access to relevant pages or user settings.
The header should be responsive, adapting to various screen sizes to ensure consistency across all devices. This will not only improve user interaction but also enhance the overall design of the web page.

![Screenshot 2024-10-07 202814](https://github.com/user-attachments/assets/c2de978f-4231-47a6-abb8-1d98bb7f190b)

**Alternatives Considered**
Adding a footer-only navigation, which could reduce the visibility of the navigation options.
Creating a side navigation menu, though this could be less accessible on certain devices compared to a header.
Additional Context
Including a header aligns with modern web design practices and helps users have a smoother experience by quickly finding the sections they need.

**Requirement/Document**
_**No additional documents**_ are currently attached. However, future design considerations might involve a wireframe or UI mockup of the proposed header for better clarity during development.

**Comment by tejasam571** [comment]
@jency1 , the assigned task is completed successfully . Please consider the pull request made . 

Thank you

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..
