### ISSUE TITLE
external links open in the same tab

### ISSUE THREAD

**Issue by GauriSachan** [multiverseweb/Dataverse#8]
hey I noticed a small issue in the site that when we try to open external links they open in the same tab which can be inconvenient at times if you want both the previous and the new page to be kept open , I can fix this issue so can you assign me this issue under gssoc-ext and hacktoberfest?

**Comment by multiverseweb** [comment]
@GauriSachan Sure, assigned.

**Comment by GauriSachan** [comment]
thank you!

**Comment by subikshabamboo** [comment]
I can contribute to this issue can you assign me this?

**Comment by multiverseweb** [comment]
@subikshabamboo sure, good luck!

**Comment by ChauhanAyush04** [comment]
plz assign me this project
