### ISSUE TITLE
Dark/Light Theme Button Does Not Reflect Selection State

### ISSUE THREAD

**Issue by thlghs** [multiverseweb/Dataverse#80]
![image](https://github.com/user-attachments/assets/49f1663a-efed-44c9-bae6-0e9616341b45)

When switching between the dark and light themes using the moon (dark) and sun (light) icons on the map, the button does not visually indicate the current selection. The expected behavior is that the selected button (e.g., the moon icon for dark mode) should visually reflect the selection state (e.g., by highlighting, shining, or changing color) to provide clear feedback to the user. allow me to make those changes please. I am well- versed in CSS.

**Comment by subodhsalgaonkar** [comment]
@jency1 Can I work on this issue?

**Comment by subodhsalgaonkar** [comment]
@jency1 I am interested to work on this issue.

**Comment by thlghs** [comment]
@jency1 I fixed the issue yesterday
