### ISSUE TITLE
FIX: The home page onhover functionality for Code Obfuscation section on website

### ISSUE THREAD

**Issue by subodhsalgaonkar** [multiverseweb/Dataverse#81]
Problem: The images on the homepage have the onhover functionality that seems to be working fine for other sections, but for the Code Obfuscation section there seems to be a problem.

https://github.com/user-attachments/assets/b80ed214-a5b3-4661-b0df-028c124252ed

I would like to work on this issue @multiverseweb.

Also some additional suggestions which I can work on:
In my opinion the navbar section does not require hyperlink to  contribute, feedback and license as the home page itself is short and it has a back to top button as well. Also in the navbar the transparent attribute seems to be fine for dark mode but for light mode while scrolling over the images it does not look good.

**Comment by multiverseweb** [comment]
@subodhsalgaonkar actually the zoom-in function on hover has been added on purpose to show the difference between normal code and obfuscated code. Do you have any better idea?
