### ISSUE TITLE
Improvement in the navbar and License section

### ISSUE THREAD

**Issue by mdthejaswini123** [multiverseweb/Dataverse#82]
I think the navbar font is too small.
Can I increase the font size? for better readability.
 And in the License  3rd paragraph, it looks clumsy .
Can I change the font style and size for better readability?

**Comment by multiverseweb** [comment]
Sure @mdthejaswini123, you can change the text case in license but I believe the font size of the nav items is fine as it matches with rest of the text in website. That's just my opinion, you can try increasing it, we'll keep it larger if it looks better.

**Comment by mdthejaswini123** [comment]
Okay, thank you.And if you want to make any particular changes to the website, please let me know.
