### ISSUE TITLE
Elevate User Experience by Introducing a Custom Cursor and increasing responsiveness 

### ISSUE THREAD

**Issue by AnujShrivastava01** [multiverseweb/Dataverse#84]
# Description:

I propose adding a custom cursor to the website to enhance the overall user experience. A visually appealing and unique cursor design can significantly increase engagement by giving the site a more polished and modern feel, differentiating it from competitors.
Also I will work on the responsiveness of website .
# Benefits:
Improved User Experience
Brand Identity Enhancement
Increased Interaction

Assign this to me .
Thankyou !

**Comment by jency1** [comment]
@AnujShrivastava01 Can you show what type of custom cursor you want to add ?

**Comment by AnujShrivastava01** [comment]
> @AnujShrivastava01 Can you show what type of custom cursor you want to add ? 

https://github.com/user-attachments/assets/9d1a101d-7333-4d97-9180-e6fcf57aa026

**Comment by multiverseweb** [comment]
Hey @AnujShrivastava01, I don't really think this type of cursor is required for dataverse. Thanks for your idea!
Good luck.
