### ISSUE TITLE
Enhance footer page styling

### ISSUE THREAD

**Issue by JOSHITHA6** [multiverseweb/Dataverse#86]
Have an idea for a new feature? Please fill out the sections below. 😊

I would love to improve on the footer page to enhance it better.

- Describe the current situation or problem you're facing. Be specific about what’s lacking or what can be improved.

I have found that the current footer is not organised , so I would love to fix the issue by enhancing the styling for footer.

- Describe the feature or enhancement you'd like to see implemented.

### Screenshot/Mockup (Optional)

![Screenshot (157)](https://github.com/user-attachments/assets/8aaffad8-e0a3-4550-9a88-c4b2cac8d616)

Please assign me this task under gssoc'24 and hacktoberfest @multiverseweb

**Comment by Shalinis19137** [comment]
I Would like to work on this project, Can you please assign me this issue under Gssoc-ext 2024
