### ISSUE TITLE
Issue Title: "Add 'Follow Us on Social Media' Section"

### ISSUE THREAD

**Issue by AswaniBolisetti** [multiverseweb/Dataverse#91]
@multiverseweb 
Issue Description: The website currently lacks a 'Follow Us on Social Media' section. I propose adding social media icons and links to platforms such as Facebook, Twitter, Instagram, and LinkedIn as a side bar, encouraging users to connect with us and stay updated.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

**Comment by Shy029** [comment]
I am also interested in this.
If possible ,please assign this issue to me also under gssoc-ext, hacktoberfest-accepted, level.

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..

**Comment by multiverseweb** [comment]
Hey @AswaniBolisetti, I'm assigning it to you. Please add icons for [Discord](https://discord.gg/d4FanYHu) and [GitHub](https://github.com/Multiverse-Web). I think adding icons in the left side-bar would look good. What do you think?

![image](https://github.com/user-attachments/assets/4ea9734d-cdab-499f-a216-d6f81a6a6cdb)

**Comment by AswaniBolisetti** [comment]
@multiverseweb Sure!

**Comment by multiverseweb** [comment]
Any updates @AswaniBolisetti?

**Comment by AswaniBolisetti** [comment]
@multiverseweb Sorry Close this
I tried but i was not able to run the code

**Comment by multiverseweb** [comment]
Oh okay, no problem.
