### ISSUE TITLE
Enhance Header Section for Improved Navigation and Visual Appeal

### ISSUE THREAD

**Issue by Shweta-1902** [multiverseweb/Dataverse#93]
Revamp the header to improve navigation and enhance its visual appeal. 
Focus on:

Smoother navigation links for easy section access.
Modern design with updated fonts, colors, and layout.
Add relevant call-to-action buttons or links.

if possible assign this to me under the label of gssoc ext and hactoberfest.

![Screenshot (389)](https://github.com/user-attachments/assets/f94f5d4d-5b8a-4cd0-bb56-77fdd6df7de8)

**Comment by jency1** [comment]
@Shweta-1902  Which links will you add ? And attach a photo of the layout which you will be making to impove the header section.
