### ISSUE TITLE
Add Scroll Progress Bar to Enhance User Experience

### ISSUE THREAD

**Issue by shashankgoud18** [multiverseweb/Dataverse#95]
I would like to propose adding a scroll progress bar at the top of the webpage to improve user experience. The progress bar will provide visual feedback to users about how much of the page they have scrolled through and how much content remains, especially useful for long pages.

https://github.com/user-attachments/assets/68747da9-61b1-4ac5-bd80-0fa6c91ef965

I have added this video for your reference

**Comment by Ishika1323** [comment]
I want to work on this

**Comment by multiverseweb** [comment]
@Ishika1323 assigned.

**Comment by shashankgoud18** [comment]
Hi @multiverseweb,

I had been occupied with some other tasks, so I couldn't get to the assigned issue earlier. The scroll progress feature is now implemented, and I'm ready to submit the PR. If you could assign the issue to me, I’ll send the PR right away.

Looking forward to your response.

Thank You
