### ISSUE TITLE
Variable naming and Error handling in software/financeTracker.py

### ISSUE THREAD

**Issue by bhavya2021245** [multiverseweb/Dataverse#97]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

**Variable Naming:** The code contains several non-descriptive variable names, such as z, l, and f1, making it difficult to understand the purpose of these variables at a glance. The lack of meaningful names reduces the overall readability and maintainability of the code.

**Error Handling:** There is minimal error handling, particularly when dealing with database connections and queries. This results in potential crashes or silent failures without informative error messages. For instance, database operations lack proper try-except blocks to handle connection errors, failed queries, or other exceptions that might arise during runtime.

### Expected Behaviour

**Variable Naming:** Variable names should be self-explanatory and indicate the purpose of the data they store. For example:
z should be replaced with failed_login_attempts.
l should be renamed to user_data_list.
f1 should be renamed to something more descriptive like first_figure.

**Error Handling:** All database interactions and other potential error points should be wrapped in try-except blocks to handle exceptions gracefully. When an error occurs, a meaningful message should be displayed or logged. This would improve the robustness of the application, helping to avoid crashes or undefined behavior.

### Proposed Solution

**Improve Variable Naming:**
Replace short, unclear variable names with more meaningful and descriptive ones. This will make the code more readable and easier to debug or maintain.
For example:
Rename z to failed_login_attempts.
Rename l to user_data_list.
Rename f1 to first_figure.

**Enhance Error Handling:**
Add try-except blocks around all database queries and other sections of code prone to failure (e.g., file operations, network calls).
Provide detailed error messages for logging purposes or user feedback when something goes wrong.

**Comment by bhavya2021245** [comment]
Can you please assign me this isssue under hacktoberfest-accepted and gssoc-ext

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..
