### ISSUE TITLE
Issues in Css of the page

### ISSUE THREAD

**Issue by rupeshv2121** [multiverseweb/Dataverse#99]
![Screenshot 2024-10-09 215130](https://github.com/user-attachments/assets/a28e1956-b7c3-4990-98a1-ac160cd4c413)
![Screenshot 2024-10-09 215227](https://github.com/user-attachments/assets/b96bd92b-5b1b-4247-aaa1-f0f5bc8e4808)
![Screenshot 2024-10-09 215252](https://github.com/user-attachments/assets/447fc93d-42b8-46fe-b0ba-2918dedb2daf)

i want to add border radius to the the button and highlighted area and make a border in the social media section and make a horizontal line

**Comment by rupeshv2121** [comment]
@jency1 I am not able to find home-style.css file 
pls help me to reach out this

**Comment by SaanyaGarg5** [comment]
you can assign me this task...

**Comment by arpit74170** [comment]
u can assign this task to  me as i done 3 website bug fixxing and i wil add some real life effect in it
